import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: 'rgba(6, 16, 15, 0.96)',
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
  },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSpacer: { width: 36 },
  content: { padding: Spacing.lg },
  label: { fontSize: 12, fontWeight: '800', color: Arena.text, marginBottom: 6, marginTop: 12 },
  input: {
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Arena.text,
    fontWeight: '700',
  },
  row: { flexDirection: 'row', gap: 12 },
  flex1: { flex: 1 },
  segmented: { flexDirection: 'row', backgroundColor: Arena.cardSoft, borderRadius: Radius.r999, padding: 3, borderWidth: 1, borderColor: Arena.line, marginTop: 6 },
  segment: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: Radius.r999 },
  segmentActive: { backgroundColor: Arena.neon },
  segmentText: { fontSize: 13, fontWeight: '700', color: Arena.textSubtle },
  segmentTextActive: { color: Arena.bgDeep, fontWeight: '900' },
  flatList: { flex: 1 },
  flatListContent: { flexGrow: 1 },
  pickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pickerBtnText: { fontSize: 13, color: Arena.text, fontWeight: '700', flexShrink: 1 },
  coordsRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 5 },
  coordsText: { fontSize: 11, color: Colors.success },
  hintRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 },
  hintText: { flex: 1, fontSize: 11, color: Arena.textMuted },
  recurringRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Arena.card,
    borderWidth: 1,
    borderColor: Arena.line,
    borderRadius: Radius.r16,
    padding: Spacing.md,
    marginTop: 16,
  },
  recurringBody: { flex: 1 },
  recurringRowActive: { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Arena.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: { backgroundColor: Arena.neon, borderColor: Arena.neon },
  recurringLabel: { fontSize: 13, fontWeight: '800', color: Arena.text },
  recurringLabelActive: { color: Arena.neon },
  recurringSub: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  topSpacer: { height: 24 },
  bottomSpacer: { height: 32 },
  submitBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r16, paddingVertical: 14, alignItems: 'center' },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: Arena.bgDeep, fontSize: 15, fontWeight: '900' },
  dangerZone: {
    gap: 10,
    backgroundColor: Arena.card,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    borderRadius: Radius.r16,
    padding: Spacing.md,
    marginTop: 18,
  },
  dangerTitle: { fontSize: 13, fontWeight: '800', color: Colors.error },
  dangerText: { fontSize: 11, color: Arena.textMuted, marginTop: 3, lineHeight: 16 },
  dangerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    borderRadius: Radius.r8,
    paddingVertical: 11,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  dangerBtnStrong: { backgroundColor: Colors.error, borderColor: Colors.error },
  dangerBtnText: { color: Colors.error, fontSize: 13, fontWeight: '800' },
  dangerBtnStrongText: { color: Colors.white, fontSize: 13, fontWeight: '800' },
  modalOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  modal: { width: '100%', backgroundColor: Arena.graphiteElevated, borderRadius: Radius.r16, padding: Spacing.lg },
  modalTitle: { fontSize: 17, fontWeight: '800', color: Arena.text },
  modalSubtitle: { fontSize: 12, color: Arena.textMuted, marginTop: 4, marginBottom: 12 },
  modalInput: {
    minHeight: 96,
    backgroundColor: Arena.card,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Arena.text,
  },
  modalButtonRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  modalBtn: { flex: 1, borderRadius: Radius.r8, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  modalBtnSecondary: { backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line },
  modalBtnDanger: { backgroundColor: Colors.error },
  modalBtnDisabled: { opacity: 0.5 },
  modalBtnTextSecondary: { color: Arena.text, fontSize: 13, fontWeight: '800' },
  modalBtnTextDanger: { color: Colors.white, fontSize: 13, fontWeight: '800' },
});
