import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
  },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSpacer: { width: 36 },
  content: { padding: Spacing.lg },
  label: { fontSize: 12, fontWeight: '600', color: Colors.n700, marginBottom: 6, marginTop: 12 },
  input: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Colors.n900,
  },
  row: { flexDirection: 'row', gap: 12 },
  flex1: { flex: 1 },
  segmented: { flexDirection: 'row', backgroundColor: Colors.n100, borderRadius: Radius.r8, padding: 3, marginTop: 6 },
  segment: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: Radius.r8 - 1 },
  segmentActive: { backgroundColor: Colors.white, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  segmentText: { fontSize: 13, fontWeight: '500', color: Colors.n500 },
  segmentTextActive: { color: Colors.primary, fontWeight: '700' },
  pickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pickerBtnText: { fontSize: 13, color: Colors.n900, fontWeight: '500', flexShrink: 1 },
  coordsRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 5 },
  coordsText: { fontSize: 11, color: Colors.successDark },
  hintRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 },
  hintText: { flex: 1, fontSize: 11, color: Colors.n400 },
  recurringRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.n200,
    borderRadius: Radius.r12,
    padding: Spacing.md,
    marginTop: 16,
  },
  recurringBody: { flex: 1 },
  recurringRowActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Colors.n300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  recurringLabel: { fontSize: 13, fontWeight: '700', color: Colors.n900 },
  recurringLabelActive: { color: Colors.primary },
  recurringSub: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  topSpacer: { height: 24 },
  bottomSpacer: { height: 32 },
  submitBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r12, paddingVertical: 14, alignItems: 'center' },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  dangerZone: {
    gap: 10,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.errorLight,
    borderRadius: Radius.r12,
    padding: Spacing.md,
    marginTop: 18,
  },
  dangerTitle: { fontSize: 13, fontWeight: '800', color: Colors.errorDark },
  dangerText: { fontSize: 11, color: Colors.n500, marginTop: 3, lineHeight: 16 },
  dangerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.errorLight,
    borderRadius: Radius.r8,
    paddingVertical: 11,
    backgroundColor: Colors.errorLight,
  },
  dangerBtnStrong: { backgroundColor: Colors.error, borderColor: Colors.error },
  dangerBtnText: { color: Colors.errorDark, fontSize: 13, fontWeight: '800' },
  dangerBtnStrongText: { color: Colors.white, fontSize: 13, fontWeight: '800' },
  modalOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  modal: { width: '100%', backgroundColor: Colors.white, borderRadius: Radius.r12, padding: Spacing.lg },
  modalTitle: { fontSize: 17, fontWeight: '800', color: Colors.n900 },
  modalSubtitle: { fontSize: 12, color: Colors.n500, marginTop: 4, marginBottom: 12 },
  modalInput: {
    minHeight: 96,
    backgroundColor: Colors.n50,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Colors.n900,
  },
  modalButtonRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  modalBtn: { flex: 1, borderRadius: Radius.r8, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  modalBtnSecondary: { backgroundColor: Colors.n100 },
  modalBtnDanger: { backgroundColor: Colors.error },
  modalBtnDisabled: { opacity: 0.5 },
  modalBtnTextSecondary: { color: Colors.n700, fontSize: 13, fontWeight: '800' },
  modalBtnTextDanger: { color: Colors.white, fontSize: 13, fontWeight: '800' },
});
