import { StyleSheet } from 'react-native';
import { Arena, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Arena.textMuted },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  primaryBtnText: { color: Arena.buttonLabelPrimary, fontWeight: '900', fontSize: 13 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Arena.graphiteElevated, borderBottomWidth: 1, borderBottomColor: Arena.line, gap: 12 },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 11, color: Arena.textMuted },
  listContent: { paddingHorizontal: Spacing.lg, paddingBottom: 28 },
  groupLabel: { fontSize: 11, fontWeight: '800', color: Arena.textSubtle, marginTop: 10, marginBottom: 6, textTransform: 'uppercase' },
  emptyCard: { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 26, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textMuted },
  favoriteRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 7, gap: 10 },
  favoriteBody: { flex: 1, minWidth: 0 },
  favoriteAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: Arena.warningBg, alignItems: 'center', justifyContent: 'center' },
  favoriteAvatarText: { fontSize: 13, fontWeight: '800', color: Arena.warning },
  favoriteName: { fontSize: 13, fontWeight: '700', color: Arena.text },
  favoriteMeta: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  favoriteRemoveBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: Arena.warningBg, alignItems: 'center', justifyContent: 'center' },
  memberRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 7, gap: 10 },
  memberBody: { flex: 1, minWidth: 0 },
  memberAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  memberAvatarAdmin: { backgroundColor: Arena.neon },
  memberAvatarText: { fontSize: 13, fontWeight: '800', color: Arena.textMuted },
  memberAvatarTextAdmin: { color: Arena.buttonLabelPrimary },
  memberNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  memberName: { fontSize: 13, fontWeight: '700', color: Arena.text, flexShrink: 1 },
  memberMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 3, flexWrap: 'wrap' },
  memberOverall: { fontSize: 11, color: Arena.textMuted },
  adminBadge: { backgroundColor: Arena.neonSoft, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  adminBadgeText: { fontSize: 10, fontWeight: '700', color: Arena.neon },
  posTag: { backgroundColor: Arena.cardSoft, borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2, borderWidth: 1, borderColor: Arena.line },
  posTagText: { fontSize: 10, fontWeight: '700', color: Arena.textMuted },
  statusTag: { borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2 },
  statusTagText: { fontSize: 10, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalSheet: { backgroundColor: Arena.graphiteElevated, borderRadius: Radius.r16, width: '100%', overflow: 'hidden' },
  modalTitle: { fontSize: 16, fontWeight: '800', color: Arena.text, textAlign: 'center', paddingTop: 20, paddingHorizontal: 16 },
  modalSub: { fontSize: 13, color: Arena.textMuted, textAlign: 'center', paddingBottom: 12, paddingHorizontal: 16 },
  modalDivider: { height: 1, backgroundColor: Arena.line },
  modalOption: { paddingVertical: 16, paddingHorizontal: 20, alignItems: 'center' },
  modalOptionText: { fontSize: 14, fontWeight: '700', color: Arena.neon },
  modalOptionDestructive: { color: Arena.error },
  modalCancelText: { fontSize: 14, fontWeight: '700', color: Arena.textMuted },
  profileOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  profileSheet: { backgroundColor: Arena.graphiteElevated, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, paddingHorizontal: Spacing.lg, paddingBottom: 32 },
  profileHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Arena.line, alignSelf: 'center', marginTop: 10, marginBottom: 16 },
  profileHeader: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 14 },
  profileAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  profileAvatarText: { fontSize: 18, fontWeight: '800', color: Arena.textMuted },
  profileBody: { flex: 1, minWidth: 0 },
  profileName: { fontSize: 16, fontWeight: '800', color: Arena.text },
  profileOvr: { alignItems: 'center', backgroundColor: Arena.neon, borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 6 },
  profileOvrNum: { fontSize: 18, fontWeight: '800', color: Arena.buttonLabelPrimary, lineHeight: 20 },
  profileOvrLbl: { fontSize: 9, fontWeight: '700', color: Arena.buttonLabelPrimary },
  profileStatsTitle: { fontSize: 12, fontWeight: '800', color: Arena.textSubtle, textTransform: 'uppercase', marginBottom: 12 },
  profileNoStats: { fontSize: 13, color: Arena.textSubtle, textAlign: 'center', paddingVertical: 8 },
  statRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  statLabel: { fontSize: 12, color: Arena.textMuted, width: 78 },
  statBarBg: { flex: 1, height: 6, backgroundColor: Arena.cardSoft, borderRadius: Radius.r999, overflow: 'hidden' },
  statBarFill: { height: '100%', borderRadius: Radius.r999, backgroundColor: Arena.neon },
  statValue: { fontSize: 11, fontWeight: '800', color: Arena.neon, width: 44, textAlign: 'right' },
  profileCloseBtn: { backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center', marginTop: 16 },
  profileCloseBtnText: { fontSize: 14, fontWeight: '800', color: Arena.text },
});
