import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Colors.n700 },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  primaryBtnText: { color: Colors.white, fontWeight: '700', fontSize: 13 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, gap: 12 },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSub: { fontSize: 11, color: Colors.n500 },
  tabs: { flexDirection: 'row', margin: Spacing.lg, backgroundColor: Colors.n100, borderRadius: Radius.r12, padding: 4 },
  tabBtn: { flex: 1, alignItems: 'center', borderRadius: Radius.r8, paddingVertical: 10 },
  tabBtnActive: { backgroundColor: Colors.white },
  tabText: { fontSize: 12, fontWeight: '700', color: Colors.n500 },
  tabTextActive: { color: Colors.primary },
  listContent: { paddingHorizontal: Spacing.lg, paddingBottom: 28 },
  groupLabel: { fontSize: 11, fontWeight: '800', color: Colors.n500, marginTop: 10, marginBottom: 6, textTransform: 'uppercase' },
  emptyCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 26, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  favoriteRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 7, gap: 10 },
  favoriteBody: { flex: 1, minWidth: 0 },
  favoriteAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.warningLight, alignItems: 'center', justifyContent: 'center' },
  favoriteAvatarText: { fontSize: 13, fontWeight: '800', color: Colors.warningDark },
  favoriteName: { fontSize: 13, fontWeight: '700', color: Colors.n900 },
  favoriteMeta: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  favoriteRemoveBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: Colors.warningLight, alignItems: 'center', justifyContent: 'center' },
  memberRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 7, gap: 10 },
  memberBody: { flex: 1, minWidth: 0 },
  memberAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.n200, alignItems: 'center', justifyContent: 'center' },
  memberAvatarAdmin: { backgroundColor: Colors.primary },
  memberAvatarText: { fontSize: 13, fontWeight: '800', color: Colors.n700 },
  memberAvatarTextAdmin: { color: Colors.white },
  memberNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  memberName: { fontSize: 13, fontWeight: '700', color: Colors.n900, flexShrink: 1 },
  memberMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 3, flexWrap: 'wrap' },
  memberOverall: { fontSize: 11, color: Colors.n500 },
  adminBadge: { backgroundColor: Colors.primaryLight, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  adminBadgeText: { fontSize: 10, fontWeight: '700', color: Colors.primary },
  posTag: { backgroundColor: Colors.n100, borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2 },
  posTagText: { fontSize: 10, fontWeight: '700', color: Colors.n700 },
  statusTag: { borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2 },
  statusTagText: { fontSize: 10, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  modalSheet: { backgroundColor: Colors.white, borderRadius: Radius.r16, width: '100%', overflow: 'hidden' },
  modalTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900, textAlign: 'center', paddingTop: 20, paddingHorizontal: 16 },
  modalSub: { fontSize: 13, color: Colors.n500, textAlign: 'center', paddingBottom: 12, paddingHorizontal: 16 },
  modalDivider: { height: 1, backgroundColor: Colors.n200 },
  modalOption: { paddingVertical: 16, paddingHorizontal: 20, alignItems: 'center' },
  modalOptionText: { fontSize: 14, fontWeight: '700', color: Colors.primary },
  modalOptionDestructive: { color: Colors.error },
  modalCancelText: { fontSize: 14, fontWeight: '700', color: Colors.n500 },
  profileOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  profileSheet: { backgroundColor: Colors.white, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, paddingHorizontal: Spacing.lg, paddingBottom: 32 },
  profileHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Colors.n300, alignSelf: 'center', marginTop: 10, marginBottom: 16 },
  profileHeader: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 14 },
  profileAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: Colors.n200, alignItems: 'center', justifyContent: 'center' },
  profileAvatarText: { fontSize: 18, fontWeight: '800', color: Colors.n700 },
  profileBody: { flex: 1, minWidth: 0 },
  profileName: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  profileOvr: { alignItems: 'center', backgroundColor: Colors.primary, borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 6 },
  profileOvrNum: { fontSize: 18, fontWeight: '800', color: Colors.white, lineHeight: 20 },
  profileOvrLbl: { fontSize: 9, fontWeight: '700', color: Colors.white },
  profileStatsTitle: { fontSize: 12, fontWeight: '800', color: Colors.n500, textTransform: 'uppercase', marginBottom: 12 },
  profileNoStats: { fontSize: 13, color: Colors.n400, textAlign: 'center', paddingVertical: 8 },
  statRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  statLabel: { fontSize: 12, color: Colors.n500, width: 78 },
  statBarBg: { flex: 1, height: 6, backgroundColor: Colors.n200, borderRadius: Radius.r999, overflow: 'hidden' },
  statBarFill: { height: '100%', borderRadius: Radius.r999, backgroundColor: Colors.primary },
  statValue: { fontSize: 11, fontWeight: '800', color: Colors.primary, width: 44, textAlign: 'right' },
  profileCloseBtn: { backgroundColor: Colors.n100, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center', marginTop: 16 },
  profileCloseBtnText: { fontSize: 14, fontWeight: '800', color: Colors.n700 },
});
