import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../../ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center' },
  scroll: { padding: Spacing.lg, paddingBottom: 88, gap: 12 },
  heroCard: { backgroundColor: Colors.white, borderRadius: Radius.r16, borderWidth: 0.5, borderColor: Colors.n200, alignItems: 'center', paddingVertical: 28, paddingHorizontal: Spacing.lg, gap: 6 },
  editBtn: { position: 'absolute', top: 12, right: 12, width: 34, height: 34, borderRadius: 17, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  avatarText: { fontSize: 26, fontWeight: '800', color: Colors.primary },
  name: { fontSize: 20, fontWeight: '800', color: Colors.n900 },
  positionText: { fontSize: 13, color: Colors.n500 },
  heroRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  ovrBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: Radius.r999, paddingHorizontal: 14, paddingVertical: 6 },
  ovrNum: { fontSize: 18, fontWeight: '800', color: Colors.white },
  ovrLbl: { fontSize: 11, fontWeight: '600', color: Colors.white },
  statusBadge: { borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 6 },
  statusText: { fontSize: 12, fontWeight: '700' },
  card: { backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 0.5, borderColor: Colors.n200, padding: Spacing.lg },
  cardTitle: { fontSize: 13, fontWeight: '800', color: Colors.n900, marginBottom: 14 },
  attrRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  attrLabel: { fontSize: 12, color: Colors.n500, width: 80 },
  attrBarBg: { flex: 1, height: 6, backgroundColor: Colors.n200, borderRadius: Radius.r999, overflow: 'hidden' },
  attrBarFill: { height: 6, borderRadius: Radius.r999 },
  attrVal: { fontSize: 12, fontWeight: '700', color: Colors.n900, width: 26, textAlign: 'right' },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 4 },
  actionLabel: { flex: 1, fontSize: 14, fontWeight: '500', color: Colors.n800 },
  actionLabelDanger: { color: Colors.error },
  divider: { height: 0.5, backgroundColor: Colors.n200, marginVertical: 12 },
});
