import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Arena.textMuted },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  primaryBtnText: { color: Arena.buttonLabelPrimary, fontWeight: '900', fontSize: 13 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Arena.graphiteElevated,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
  },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 11, color: Arena.textMuted },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center' },
  listContent: { padding: Spacing.lg, paddingBottom: 28 },
  separator: { height: 8 },
  emptyCard: { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 28, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textMuted },
  emptyAction: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  emptyActionText: { color: Arena.buttonLabelPrimary, fontWeight: '900', fontSize: 13 },
  matchCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, gap: 12 },
  matchDateBox: { width: 44, alignItems: 'center', backgroundColor: Arena.neonSoft, borderRadius: Radius.r8, paddingVertical: 6 },
  matchDay: { fontSize: 9, fontWeight: '700', color: Arena.neon },
  matchDayNum: { fontSize: 18, fontWeight: '800', color: Arena.neon },
  matchBody: { flex: 1, minWidth: 0 },
  matchLocation: { fontSize: 13, fontWeight: '700', color: Arena.text },
  matchTime: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  matchSpots: { alignItems: 'center' },
  matchSpotsNum: { fontSize: 14, fontWeight: '800' },
  matchSpotsLabel: { fontSize: 10, color: Arena.textMuted },
});
