import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Arena.bg,
  },
  fieldGlow: {
    position: 'absolute',
    top: -150,
    right: -120,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: Arena.cyanSoft,
  },
  header: {
    backgroundColor: Arena.bg,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.neonBorder,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  appLogo: {
    width: 42,
    height: 42,
    borderRadius: Radius.r12,
    backgroundColor: Arena.cardSoft,
  },
  appName: {
    flexShrink: 1,
    color: Arena.text,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  headerRight: { alignItems: 'flex-end', gap: Spacing.sm },
  msgBtn: {
    position: 'relative',
    padding: 8,
    borderRadius: Radius.r999,
    backgroundColor: Arena.cardSoft,
    borderWidth: 1,
    borderColor: Arena.line,
  },
  badge: {
    position: 'absolute',
    top: 1,
    right: 1,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error,
    borderWidth: 2,
    borderColor: Arena.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { fontSize: 8, fontWeight: '900', color: Colors.white },
  scroll: { flex: 1 },
  section: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: Spacing.xxl },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: Arena.textMuted,
    marginBottom: Spacing.md,
  },
  emptyCard: {
    backgroundColor: Arena.card,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: Arena.line,
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 18,
    marginBottom: Spacing.sm,
  },
  emptyText: {
    fontSize: 13,
    color: Arena.textMuted,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 19,
    fontWeight: '700',
  },
  favoriteCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Arena.card,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
  },
  favoriteCardLeft: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  favoriteCardLabel: { fontSize: 11, fontWeight: '900', color: Colors.warning },
  favoriteCardRight: { flexDirection: 'row', alignItems: 'center', gap: 4, flex: 1, justifyContent: 'flex-end' },
  favoriteCardName: { fontSize: 13, fontWeight: '900', color: Arena.text, flexShrink: 1 },
  debtCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    padding: Spacing.md,
  },
  debtTitle: { fontSize: 13, fontWeight: '900', color: Colors.error },
  debtText: { fontSize: 11, color: 'rgba(254, 226, 226, 0.86)', marginTop: 2, lineHeight: 15 },
});
