import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.lg,
    backgroundColor: Arena.bg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.neonBorder,
  },
  headerTitle: { fontSize: 20, fontWeight: '900', color: Arena.text },
  headerSub: { fontSize: 12, color: Arena.textMuted, marginTop: 2 },
  list: { flex: 1 },
  listContent: { padding: Spacing.lg, paddingBottom: Spacing.xl, gap: 12 },
  lockCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: Colors.errorLight,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.error,
    padding: Spacing.md,
  },
  lockBody: { flex: 1 },
  lockTitle: { fontSize: 14, fontWeight: '900', color: Colors.errorDark },
  lockText: { fontSize: 12, color: Colors.errorDark, marginTop: 2, lineHeight: 16 },
  financeBtn: { backgroundColor: Colors.white, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 8 },
  financeBtnText: { color: Colors.errorDark, fontWeight: '900', fontSize: 12 },
  infoCard: {
    alignItems: 'center',
    backgroundColor: Colors.warningLight,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.warning,
    padding: Spacing.lg,
    gap: 6,
  },
  infoTitle: { fontSize: 14, fontWeight: '900', color: Colors.warningDark },
  infoText: { fontSize: 12, color: Colors.warningDark, textAlign: 'center' },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: Arena.line,
    paddingVertical: 34,
    paddingHorizontal: Spacing.md,
    gap: 8,
  },
  emptyText: { fontSize: 13, color: Arena.textMuted, fontWeight: '800', textAlign: 'center' },
  card: {
    backgroundColor: Arena.card,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: Arena.line,
    padding: Spacing.md,
    gap: 12,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconBox: {
    width: 38,
    height: 38,
    borderRadius: Radius.r8,
    backgroundColor: Arena.neonSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1 },
  cardTitle: { fontSize: 15, fontWeight: '900', color: Arena.text },
  cardSub: { fontSize: 12, color: Arena.textMuted, marginTop: 2 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  infoLineText: { fontSize: 12, fontWeight: '800', color: Arena.textMuted },
  criteria: { fontSize: 11, fontWeight: '800', color: Arena.textSubtle },
  actions: { flexDirection: 'row', gap: 10 },
  secondaryBtn: {
    flex: 1,
    alignItems: 'center',
    borderRadius: Radius.r12,
    backgroundColor: Arena.cardSoft,
    paddingVertical: 11,
  },
  secondaryBtnText: { color: Arena.text, fontWeight: '900' },
  primaryBtn: {
    alignItems: 'center',
    borderRadius: Radius.r12,
    backgroundColor: Arena.neon,
    paddingVertical: 11,
    paddingHorizontal: 12,
  },
  primaryBtnExpanded: { flex: 1 },
  disabledBtn: { opacity: 0.65 },
  primaryBtnText: { color: Arena.bgDeep, fontWeight: '900' },
});
