import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.lg,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
  },
  headerTitle: { fontSize: 18, fontWeight: '900', color: Colors.n900 },
  headerSub: { fontSize: 12, color: Colors.n500, marginTop: 2 },
  tabs: { flexDirection: 'row', gap: 8, padding: Spacing.lg, backgroundColor: Colors.white },
  tabBtn: {
    flex: 1,
    borderRadius: Radius.r8,
    backgroundColor: Colors.n100,
    alignItems: 'center',
    paddingVertical: 10,
  },
  tabBtnActive: { backgroundColor: Colors.primary },
  tabText: { fontSize: 12, fontWeight: '900', color: Colors.n600 },
  tabTextActive: { color: Colors.white },
  list: { flex: 1 },
  listContent: { padding: Spacing.lg, paddingBottom: Spacing.xl, gap: 12 },
  lockCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: Colors.errorLight,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.error,
    padding: Spacing.md,
  },
  lockBody: { flex: 1 },
  lockTitle: { fontSize: 14, fontWeight: '900', color: Colors.errorDark },
  lockText: { fontSize: 12, color: Colors.errorDark, marginTop: 2, lineHeight: 16 },
  financeBtn: { backgroundColor: Colors.white, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 8 },
  financeBtnText: { color: Colors.errorDark, fontWeight: '900', fontSize: 12 },
  infoCard: {
    alignItems: 'center',
    backgroundColor: Colors.warningLight,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.warning,
    padding: Spacing.lg,
    gap: 6,
  },
  infoTitle: { fontSize: 14, fontWeight: '900', color: Colors.warningDark },
  infoText: { fontSize: 12, color: Colors.warningDark, textAlign: 'center' },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.n200,
    paddingVertical: 34,
    paddingHorizontal: Spacing.md,
    gap: 8,
  },
  emptyText: { fontSize: 13, color: Colors.n500, fontWeight: '700', textAlign: 'center' },
  card: {
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.n200,
    padding: Spacing.md,
    gap: 12,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconBox: {
    width: 38,
    height: 38,
    borderRadius: Radius.r8,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1 },
  cardTitle: { fontSize: 15, fontWeight: '900', color: Colors.n900 },
  cardSub: { fontSize: 12, color: Colors.n500, marginTop: 2 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  infoLineText: { fontSize: 12, fontWeight: '700', color: Colors.n700 },
  criteria: { fontSize: 11, fontWeight: '700', color: Colors.n500 },
  actions: { flexDirection: 'row', gap: 10 },
  secondaryBtn: {
    flex: 1,
    alignItems: 'center',
    borderRadius: Radius.r8,
    backgroundColor: Colors.n100,
    paddingVertical: 11,
  },
  secondaryBtnText: { color: Colors.n700, fontWeight: '900' },
  primaryBtn: {
    alignItems: 'center',
    borderRadius: Radius.r8,
    backgroundColor: Colors.primary,
    paddingVertical: 11,
    paddingHorizontal: 12,
  },
  primaryBtnExpanded: { flex: 1 },
  disabledBtn: { opacity: 0.65 },
  primaryBtnText: { color: Colors.white, fontWeight: '900' },
});
