import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  keyboard: { flex: 1 },
  scroll: { padding: Spacing.lg, paddingBottom: 40 },
  stepTitle: { fontSize: 22, fontWeight: '800', color: Colors.n900, marginBottom: 4 },
  stepSubtitle: { fontSize: 13, color: Colors.n500, marginBottom: 20 },
  input: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: Colors.n900,
  },
  row: { flexDirection: 'row', alignItems: 'flex-start' },
  rowLeft: { flex: 1, marginRight: 8 },
  rowLeftWide: { flex: 2, marginRight: 8 },
  rowRight: { flex: 1 },
  rowRightWide: { flex: 2 },
  divider: { height: 1, backgroundColor: Colors.n200, marginVertical: 16 },
  sectionLabel: { fontSize: 13, fontWeight: '700', color: Colors.n700, marginBottom: 10 },
  sectionLabelSpaced: { marginTop: 16 },
  overallCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 2,
    padding: 16,
    marginBottom: 24,
  },
  overallLabel: { fontSize: 13, fontWeight: '600', color: Colors.n700 },
  overallValue: { fontSize: 36, fontWeight: '800' },
  btn: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.r12,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 8,
  },
  btnDisabled: { opacity: 0.7 },
  btnText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  daysList: { gap: 8, marginBottom: 4 },
  dayChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Colors.n300,
    backgroundColor: Colors.white,
  },
  dayChipActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  dayChipText: { fontSize: 11, fontWeight: '600', color: Colors.n700 },
  dayChipTextActive: { color: Colors.primary },
  slotList: { marginTop: 16 },
  slotCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.n200,
    padding: 16,
    marginBottom: 12,
  },
  slotCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  slotDayLabel: { fontSize: 15, fontWeight: '700', color: Colors.n900 },
  slotRemove: { fontSize: 13, fontWeight: '600', color: Colors.error },
  slotTimeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  timeBlock: { flex: 1 },
  timeLabel: { fontSize: 12, fontWeight: '600', color: Colors.n500, marginBottom: 6 },
  timeDiv: { paddingHorizontal: 12, justifyContent: 'flex-end', paddingBottom: 10 },
  timeDivText: { fontSize: 13, color: Colors.n500 },
  emptySlots: { alignItems: 'center', paddingVertical: 16 },
  emptySlotsText: { fontSize: 13, color: Colors.n400 },
});
