import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  keyboard: { flex: 1 },
  scroll: { padding: Spacing.lg, paddingBottom: 40 },
  stepTitle: { fontSize: 22, fontWeight: '800', color: Arena.text, marginBottom: 4 },
  stepSubtitle: { fontSize: 13, color: Arena.textMuted, marginBottom: 20 },
  input: {
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Arena.text,
    fontWeight: '700',
  },
  row: { flexDirection: 'row', alignItems: 'flex-start' },
  rowLeft: { flex: 1, marginRight: 8 },
  rowLeftWide: { flex: 2, marginRight: 8 },
  rowRight: { flex: 1 },
  rowRightWide: { flex: 2 },
  divider: { height: 1, backgroundColor: Arena.line, marginVertical: 16 },
  sectionLabel: { fontSize: 13, fontWeight: '700', color: Arena.text, marginBottom: 10 },
  sectionLabelSpaced: { marginTop: 16 },
  overallCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Arena.graphiteElevated,
    borderRadius: Radius.r12,
    borderWidth: 2,
    padding: 16,
    marginBottom: 24,
  },
  overallLabel: { fontSize: 13, fontWeight: '800', color: Arena.text },
  overallValue: { fontSize: 36, fontWeight: '800' },
  btn: {
    backgroundColor: Arena.neon,
    borderRadius: Radius.r16,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 8,
  },
  btnDisabled: { opacity: 0.7 },
  btnText: { color: Arena.bgDeep, fontSize: 15, fontWeight: '900' },
  daysList: { gap: 8, marginBottom: 4 },
  dayChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Arena.line,
    backgroundColor: Arena.card,
    marginRight: 8,
  },
  dayChipActive: { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  dayChipText: { fontSize: 11, fontWeight: '600', color: Arena.textMuted },
  dayChipTextActive: { color: Arena.neon, fontWeight: '800' },
  slotList: { marginTop: 16 },
  slotCard: {
    backgroundColor: Arena.graphiteElevated,
    borderRadius: Radius.r12,
    borderWidth: 1.5,
    borderColor: Arena.line,
    padding: 16,
    marginBottom: 12,
  },
  slotCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  slotDayLabel: { fontSize: 15, fontWeight: '800', color: Arena.text },
  slotRemove: { fontSize: 13, fontWeight: '700', color: Colors.error },
  slotTimeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  timeBlock: { flex: 1 },
  timeLabel: { fontSize: 12, fontWeight: '800', color: Arena.text, marginBottom: 6 },
  timeDiv: { paddingHorizontal: 12, justifyContent: 'flex-end', paddingBottom: 10 },
  timeDivText: { fontSize: 13, color: Arena.textSubtle },
  emptySlots: { alignItems: 'center', paddingVertical: 16 },
  emptySlotsText: { fontSize: 13, color: Arena.textSubtle },
});
