import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.r24,
    borderTopRightRadius: Radius.r24,
    maxHeight: '80%',
  },
  handle: {
    width: 36,
    height: 4,
    backgroundColor: Colors.n300,
    borderRadius: Radius.r999,
    alignSelf: 'center',
    marginTop: Spacing.sm,
    marginBottom: Spacing.md,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.n200,
  },
  sheetTitle: { fontSize: 16, fontWeight: '700', color: Colors.n900 },
  headerActions: { flexDirection: 'row', gap: Spacing.md, alignItems: 'center' },
  actionText: { fontSize: 12, fontWeight: '600', color: Colors.primary },
  deleteAllText: { fontSize: 12, fontWeight: '600', color: Colors.errorDark },
  list: { paddingHorizontal: Spacing.lg },
  emptyWrap: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 14, color: Colors.n400, marginTop: 8 },
  // swipeable row
  notifRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.n200,
    backgroundColor: Colors.white,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    marginTop: 5,
    flexShrink: 0,
  },
  dotRead: { backgroundColor: Colors.n300 },
  notifContent: { flex: 1 },
  notifTitle: { fontSize: 13, fontWeight: '600', color: Colors.n900 },
  notifTitleRead: { color: Colors.n500, fontWeight: '400' },
  notifBody: { fontSize: 12, color: Colors.n500, marginTop: 1, lineHeight: 16 },
  notifTime: { fontSize: 10, color: Colors.n400, marginTop: 3 },
  swipeDelete: {
    backgroundColor: Colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    width: 72,
    borderRadius: Radius.r8,
    marginVertical: 4,
  },
  swipeDeleteText: { color: Colors.white, fontSize: 11, fontWeight: '700', marginTop: 2 },
});
