import { StyleSheet } from 'react-native';
import { Arena, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Arena.textMuted },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  primaryBtnText: { color: Arena.buttonLabelPrimary, fontSize: 13, fontWeight: '900' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Arena.graphiteElevated,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
  },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 11, color: Arena.textMuted },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center' },
  scroll: { paddingBottom: 28 },
  actionsRow: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: Arena.card, paddingVertical: Spacing.md, borderBottomWidth: 1, borderBottomColor: Arena.line },
  quickAction: { alignItems: 'center', gap: 6, minWidth: 76 },
  quickActionIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: Arena.neonSoft, alignItems: 'center', justifyContent: 'center' },
  quickActionLabel: { fontSize: 11, fontWeight: '700', color: Arena.textMuted },
  reviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    backgroundColor: Arena.card,
    borderWidth: 1,
    borderColor: Arena.warningBg,
    borderRadius: Radius.r12,
    padding: Spacing.md,
  },
  reviewIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: Arena.warningBg, alignItems: 'center', justifyContent: 'center' },
  reviewBody: { flex: 1, minWidth: 0 },
  reviewTitle: { fontSize: 13, fontWeight: '900', color: Arena.text },
  reviewText: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  summaryCard: { width: '48%', minHeight: 118, backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: 14, gap: 4 },
  summaryValue: { fontSize: 19, fontWeight: '800', color: Arena.text, marginTop: 4 },
  summaryLabel: { fontSize: 12, fontWeight: '700', color: Arena.textMuted },
  summarySub: { fontSize: 11, color: Arena.textSubtle },
  section: { paddingHorizontal: Spacing.lg },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: Arena.text },
  sectionLink: { fontSize: 12, fontWeight: '700', color: Arena.neon },
  emptyCard: { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textMuted },
  emptyAction: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  emptyActionText: { color: Arena.buttonLabelPrimary, fontWeight: '900', fontSize: 13 },
  matchCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, gap: 12 },
  matchDateBox: { width: 44, alignItems: 'center', backgroundColor: Arena.neonSoft, borderRadius: Radius.r8, paddingVertical: 6 },
  matchDay: { fontSize: 9, fontWeight: '700', color: Arena.neon },
  matchDayNum: { fontSize: 18, fontWeight: '800', color: Arena.neon },
  matchBody: { flex: 1, minWidth: 0 },
  matchLocation: { fontSize: 13, fontWeight: '700', color: Arena.text },
  matchTime: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  matchSpots: { alignItems: 'center' },
  matchSpotsNum: { fontSize: 14, fontWeight: '800', color: Arena.success },
  matchSpotsLabel: { fontSize: 10, color: Arena.textMuted },
});
