import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../../ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Colors.n700 },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  primaryBtnText: { color: Colors.white, fontSize: 13, fontWeight: '700' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    gap: 12,
  },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSub: { fontSize: 11, color: Colors.n500 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  scroll: { paddingBottom: 28 },
  actionsRow: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: Colors.white, paddingVertical: Spacing.md, borderBottomWidth: 1, borderBottomColor: Colors.n200 },
  quickAction: { alignItems: 'center', gap: 6, minWidth: 76 },
  quickActionIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  quickActionLabel: { fontSize: 11, fontWeight: '700', color: Colors.n700 },
  reviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.warningLight,
    borderRadius: Radius.r12,
    padding: Spacing.md,
  },
  reviewIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: Colors.warningLight, alignItems: 'center', justifyContent: 'center' },
  reviewBody: { flex: 1, minWidth: 0 },
  reviewTitle: { fontSize: 13, fontWeight: '900', color: Colors.n900 },
  reviewText: { fontSize: 11, color: Colors.n600, marginTop: 2 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  summaryCard: { width: '48%', minHeight: 118, backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 14, gap: 4 },
  summaryValue: { fontSize: 19, fontWeight: '800', color: Colors.n900, marginTop: 4 },
  summaryLabel: { fontSize: 12, fontWeight: '700', color: Colors.n700 },
  summarySub: { fontSize: 11, color: Colors.n500 },
  section: { paddingHorizontal: Spacing.lg },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: Colors.n900 },
  sectionLink: { fontSize: 12, fontWeight: '700', color: Colors.primary },
  emptyCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  emptyAction: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  emptyActionText: { color: Colors.white, fontWeight: '700', fontSize: 13 },
  matchCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, gap: 12 },
  matchDateBox: { width: 44, alignItems: 'center', backgroundColor: Colors.primaryLight, borderRadius: Radius.r8, paddingVertical: 6 },
  matchDay: { fontSize: 9, fontWeight: '700', color: Colors.primary },
  matchDayNum: { fontSize: 18, fontWeight: '800', color: Colors.primary },
  matchBody: { flex: 1, minWidth: 0 },
  matchLocation: { fontSize: 13, fontWeight: '700', color: Colors.n900 },
  matchTime: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  matchSpots: { alignItems: 'center' },
  matchSpotsNum: { fontSize: 14, fontWeight: '800', color: Colors.success },
  matchSpotsLabel: { fontSize: 10, color: Colors.n500 },
});
