import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center', gap: 8 },
  errorText: { fontSize: 14, color: Colors.n700 },
  primaryBtn: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 10, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  primaryBtnText: { color: Colors.white, fontWeight: '700', fontSize: 13 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    gap: 12,
  },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSub: { fontSize: 11, color: Colors.n500 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  listContent: { padding: Spacing.lg, paddingBottom: 28 },
  separator: { height: 8 },
  emptyCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 28, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  emptyAction: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  emptyActionText: { color: Colors.white, fontWeight: '700', fontSize: 13 },
  matchCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, gap: 12 },
  matchDateBox: { width: 44, alignItems: 'center', backgroundColor: Colors.primaryLight, borderRadius: Radius.r8, paddingVertical: 6 },
  matchDay: { fontSize: 9, fontWeight: '700', color: Colors.primary },
  matchDayNum: { fontSize: 18, fontWeight: '800', color: Colors.primary },
  matchBody: { flex: 1, minWidth: 0 },
  matchLocation: { fontSize: 13, fontWeight: '700', color: Colors.n900 },
  matchTime: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  matchSpots: { alignItems: 'center' },
  matchSpotsNum: { fontSize: 14, fontWeight: '800' },
  matchSpotsLabel: { fontSize: 10, color: Colors.n500 },
});
