import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '@ui/tokens/theme';

export const s = StyleSheet.create({
  safe:        { flex: 1, backgroundColor: Colors.n50 },
  scrollContent: { flexGrow: 1, paddingBottom: 20 },
  center:      { justifyContent: 'center', alignItems: 'center', gap: 8 },
  rowContent:  { flex: 1, minWidth: 0 },
  errorText:   { fontSize: 14, color: Colors.n700 },
  retryBtn:    { marginTop: 8, paddingHorizontal: 20, paddingVertical: 10, backgroundColor: Colors.primary, borderRadius: Radius.r8 },
  retryText:   { color: Colors.white, fontWeight: '600' },

  header:      { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, gap: 12, minHeight: 56 },
  backBtn:     { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 15, fontWeight: '800', color: Colors.n900 },
  headerSub:   { fontSize: 11, color: Colors.n500, textTransform: 'capitalize' },
  editBtn:     { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },

  infoCard:    { backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, padding: Spacing.lg, gap: 12 },
  infoRow:     { flexDirection: 'row', alignItems: 'center' },
  infoItem:    { flex: 1, alignItems: 'center', gap: 2 },
  infoValue:   { fontSize: 15, fontWeight: '800', color: Colors.n900 },
  infoLabel:   { fontSize: 10, color: Colors.n500 },
  infoDivider: { width: 1, height: 36, backgroundColor: Colors.n200 },
  statusBadge: { alignSelf: 'flex-start', borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 4 },
  statusBadgeText: { fontSize: 12, fontWeight: '700' },
  liveMatchBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Colors.error, borderRadius: Radius.r12, paddingVertical: 13 },
  liveMatchBtnText: { color: Colors.white, fontSize: 14, fontWeight: '800' },

  section:      { marginTop: Spacing.lg, paddingHorizontal: Spacing.lg },
  sectionHeader:{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: Colors.n900, marginBottom: 10 },

  counterCard:  { flexDirection: 'row', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, marginBottom: 10 },
  counterItem:  { flex: 1, alignItems: 'center', paddingVertical: 12, gap: 2 },
  counterValue: { fontSize: 22, fontWeight: '800' },
  counterLabel: { fontSize: 10, color: Colors.n500 },

  progressBg:   { height: 6, backgroundColor: Colors.n200, borderRadius: Radius.r999, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: Colors.primary, borderRadius: Radius.r999 },
  progressLabel:{ fontSize: 11, color: Colors.n500, marginTop: 6, textAlign: 'right' },
  hintBox:      { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Colors.warningLight, borderRadius: Radius.r8, padding: 10, marginTop: 10 },
  hintText:     { flex: 1, fontSize: 12, fontWeight: '700', color: Colors.warningDark },

  emptyCard:    { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 20 },
  emptyText:    { fontSize: 13, color: Colors.n400 },

  presenceRow:      { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 6, gap: 10 },
  presenceAvatar:   { width: 38, height: 38, borderRadius: 19, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  presenceAvatarText:{ fontSize: 12, fontWeight: '800', color: Colors.primary },
  presenceNameRow:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  presenceName:     { fontSize: 13, fontWeight: '600', color: Colors.n900 },
  presenceSub:      { fontSize: 11, color: Colors.n500, marginTop: 2 },
  presenceBadge:    { flexDirection: 'row', alignItems: 'center', gap: 3, borderRadius: Radius.r999, paddingHorizontal: 8, paddingVertical: 4 },
  presenceBadgeText:{ fontSize: 11, fontWeight: '600' },
  guestTag:         { backgroundColor: Colors.n100, borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2 },
  guestTagText:     { fontSize: 10, fontWeight: '600', color: Colors.n700 },

  searchWrap:    { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r8, borderWidth: 1, borderColor: Colors.n300, paddingHorizontal: 10, marginBottom: 8, gap: 6 },
  searchIcon:    { flexShrink: 0 },
  searchInput:   { flex: 1, fontSize: 14, color: Colors.n900, paddingVertical: 9 },

  guestFilters:  { backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 10 },
  filterRow:     { flexDirection: 'row', gap: 10, marginBottom: 8 },
  filterLabel:   { fontSize: 11, fontWeight: '600', color: Colors.n700, marginBottom: 4 },
  filterInput:   { backgroundColor: Colors.n50, borderWidth: 1, borderColor: Colors.n300, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14, color: Colors.n900 },
  flex1:         { flex: 1 },

  genderRow:         { flexDirection: 'row', gap: 8, marginTop: 4 },
  genderChip:        { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: Radius.r8, borderWidth: 1, borderColor: Colors.n300, backgroundColor: Colors.white },
  genderChipActive:  { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  genderChipText:    { fontSize: 12, fontWeight: '500', color: Colors.n700 },
  genderChipTextActive: { color: Colors.primary, fontWeight: '700' },

  athleteCounter:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.primaryLight, borderRadius: Radius.r12, padding: Spacing.md, marginBottom: 8 },
  athleteCounterLeft:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  athleteCounterNum:   { fontSize: 22, fontWeight: '800', color: Colors.primary },
  athleteCounterLabel: { fontSize: 13, fontWeight: '500', color: Colors.primary },
  athleteCounterSub:   { fontSize: 12, color: Colors.primaryDark, fontWeight: '600' },

  guestRow:        { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 6, gap: 10 },
  guestRowSelected: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  applicationRow:  { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, marginBottom: 6, gap: 10 },
  applicationActions: { flexDirection: 'row', gap: 6 },
  applicationBtn:  { width: 34, height: 34, borderRadius: Radius.r8, alignItems: 'center', justifyContent: 'center' },
  applicationAccept: { backgroundColor: Colors.successLight },
  applicationDecline: { backgroundColor: Colors.errorLight },
  applicationWarning: { fontSize: 11, color: Colors.errorDark, fontWeight: '700', marginTop: 2 },
  selectCircle:    { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: Colors.n300, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.white },
  selectCircleActive: { borderColor: Colors.primary, backgroundColor: Colors.primary },
  guestAvatar:     { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  guestAvatarText: { fontSize: 13, fontWeight: '800', color: Colors.primary },
  guestName:       { fontSize: 13, fontWeight: '600', color: Colors.n900 },
  guestSub:        { fontSize: 11, color: Colors.n500, marginTop: 2 },
  ovrBadge:        { borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 4, alignItems: 'center' },
  ovrHigh:         { backgroundColor: Colors.successLight },
  ovrMid:          { backgroundColor: Colors.warningLight },
  ovrLow:          { backgroundColor: Colors.errorLight },
  ovrText:         { fontSize: 12, fontWeight: '800', color: Colors.n900 },
  favoriteBtn:     { width: 34, height: 34, borderRadius: 17, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  favoriteBtnActive: { backgroundColor: Colors.warningLight },

  paymentCard:     { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, gap: 10 },
  paymentTitle:    { fontSize: 13, fontWeight: '800', color: Colors.n900 },
  paymentText:     { fontSize: 12, color: Colors.n500, marginTop: 2 },
  paymentBtn:      { backgroundColor: Colors.primary, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 9 },
  paymentBtnText:  { color: Colors.white, fontSize: 12, fontWeight: '700' },

  matchActionsCard: { backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: Spacing.md, gap: 10 },
  inlineActionRow:  { flexDirection: 'row', alignItems: 'center', gap: 8 },
  secondaryActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: Colors.primaryLight, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 10 },
  secondaryActionDone: { backgroundColor: Colors.successLight },
  secondaryActionDanger: { backgroundColor: Colors.errorLight },
  secondaryActionText: { fontSize: 12, fontWeight: '700', color: Colors.primary },
  smallPrimaryBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 10 },
  smallPrimaryText: { fontSize: 12, fontWeight: '700', color: Colors.white },
  teamsWrap:       { gap: 8 },
  teamsDiff:       { fontSize: 11, fontWeight: '700', color: Colors.n500 },
  teamBox:         { backgroundColor: Colors.n50, borderRadius: Radius.r8, borderWidth: 1, borderColor: Colors.n200, padding: 10 },
  myTeamBox:       { backgroundColor: Colors.primaryLight, borderColor: Colors.primary },
  teamTitle:       { fontSize: 12, fontWeight: '800', color: Colors.n900, marginBottom: 4 },
  myTeamTitle:     { color: Colors.primary },
  teamAthlete:     { fontSize: 11, color: Colors.n600, marginTop: 2 },
  inviteBtn:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Colors.primary, borderRadius: Radius.r12, paddingVertical: 13 },
  inviteBtnDisabled: { opacity: 0.6 },
  inviteBtnText:     { color: Colors.white, fontSize: 14, fontWeight: '700' },

  adminActionsRow:   { flexDirection: 'row', gap: 10, marginTop: 12 },
  actionBtn:         { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: Radius.r8, paddingVertical: 10 },
  actionBtnCancel:   { backgroundColor: Colors.errorLight, borderWidth: 1, borderColor: Colors.error },
  actionBtnFinish:   { backgroundColor: Colors.successLight, borderWidth: 1, borderColor: Colors.success },
  actionBtnTextCancel: { fontSize: 12, fontWeight: '700', color: Colors.errorDark },
  actionBtnTextFinish: { fontSize: 12, fontWeight: '700', color: Colors.successDark },

  modalOverlay:      { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end', alignItems: 'center' },
  modal:             { backgroundColor: Colors.white, borderTopLeftRadius: Radius.r16, borderTopRightRadius: Radius.r16, padding: Spacing.lg, width: '100%', maxHeight: '80%' },
  modalTitle:        { fontSize: 16, fontWeight: '800', color: Colors.n900, marginBottom: 4 },
  modalSubtitle:     { fontSize: 13, color: Colors.n500, marginBottom: 16 },
  modalInput:        { backgroundColor: Colors.n50, borderWidth: 1, borderColor: Colors.n300, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 12, fontSize: 14, color: Colors.n900, marginBottom: 8, maxHeight: 120 },
  modalCharCount:    { fontSize: 11, color: Colors.n500, marginBottom: 16, textAlign: 'right' },
  modalButtonRow:    { flexDirection: 'row', gap: 10 },
  modalBtn:          { flex: 1, paddingVertical: 12, borderRadius: Radius.r8, alignItems: 'center', justifyContent: 'center' },
  modalBtnPrimary:   { backgroundColor: Colors.primary },
  modalBtnSecondary: { backgroundColor: Colors.n100, borderWidth: 1, borderColor: Colors.n300 },
  modalBtnTextPrimary: { color: Colors.white, fontSize: 14, fontWeight: '700' },
  modalBtnTextSecondary: { color: Colors.n700, fontSize: 14, fontWeight: '700' },
  modalBtnDisabled:  { opacity: 0.5 },
});
