import { StyleSheet } from 'react-native';
import { Arena, Radius, Spacing } from '@ui/tokens/theme';

export const s = StyleSheet.create({
  safe:        { flex: 1, backgroundColor: Arena.bg },
  scrollContent: { flexGrow: 1, paddingBottom: 20 },
  center:      { justifyContent: 'center', alignItems: 'center', gap: 8 },
  rowContent:  { flex: 1, minWidth: 0 },
  errorText:   { fontSize: 14, color: Arena.textMuted },
  retryBtn:    { marginTop: 8, paddingHorizontal: 20, paddingVertical: 10, backgroundColor: Arena.neon, borderRadius: Radius.r8 },
  retryText:   { color: Arena.bgDeep, fontWeight: '800' },

  header:      { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Arena.graphiteElevated, borderBottomWidth: 1, borderBottomColor: Arena.line, gap: 12, minHeight: 56 },
  backBtn:     { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 15, fontWeight: '800', color: Arena.text },
  headerSub:   { fontSize: 11, color: Arena.textMuted, textTransform: 'capitalize' },
  editBtn:     { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center' },

  infoCard:    { backgroundColor: Arena.card, borderBottomWidth: 1, borderBottomColor: Arena.line, padding: Spacing.lg, gap: 12 },
  infoRow:     { flexDirection: 'row', alignItems: 'center' },
  infoItem:    { flex: 1, alignItems: 'center', gap: 2 },
  infoValue:   { fontSize: 15, fontWeight: '800', color: Arena.text },
  infoLabel:   { fontSize: 10, color: Arena.textSubtle },
  infoDivider: { width: 1, height: 36, backgroundColor: Arena.line },
  statusBadge: { alignSelf: 'flex-start', borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 4 },
  statusBadgeText: { fontSize: 12, fontWeight: '700' },
  liveMatchBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Arena.error, borderRadius: Radius.r12, paddingVertical: 13 },
  liveMatchBtnText: { color: Arena.buttonLabelPrimary, fontSize: 14, fontWeight: '800' },

  section:      { marginTop: Spacing.lg, paddingHorizontal: Spacing.lg },
  sectionHeader:{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: Arena.text, marginBottom: 10 },

  counterCard:  { flexDirection: 'row', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, marginBottom: 10 },
  counterItem:  { flex: 1, alignItems: 'center', paddingVertical: 12, gap: 2 },
  counterValue: { fontSize: 22, fontWeight: '800', color: Arena.text },
  counterLabel: { fontSize: 10, color: Arena.textSubtle },

  progressBg:   { height: 6, backgroundColor: Arena.line, borderRadius: Radius.r999, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: Arena.neon, borderRadius: Radius.r999 },
  progressLabel:{ fontSize: 11, color: Arena.textMuted, marginTop: 6, textAlign: 'right' },
  hintBox:      { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Arena.warningBg, borderRadius: Radius.r8, padding: 10, marginTop: 10, borderWidth: 1, borderColor: Arena.warningBg },
  hintText:     { flex: 1, fontSize: 12, fontWeight: '700', color: Arena.warning },

  emptyCard:    { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 20 },
  emptyText:    { fontSize: 13, color: Arena.textMuted },

  presenceRow:      { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 6, gap: 10 },
  presenceAvatar:   { width: 38, height: 38, borderRadius: 19, backgroundColor: Arena.neonSoft, alignItems: 'center', justifyContent: 'center' },
  presenceAvatarText:{ fontSize: 12, fontWeight: '800', color: Arena.neon },
  presenceNameRow:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  presenceName:     { fontSize: 13, fontWeight: '600', color: Arena.text },
  presenceSub:      { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  presenceBadge:    { flexDirection: 'row', alignItems: 'center', gap: 3, borderRadius: Radius.r999, paddingHorizontal: 8, paddingVertical: 4 },
  presenceBadgeText:{ fontSize: 11, fontWeight: '600' },
  guestTag:         { backgroundColor: Arena.line, borderRadius: Radius.r4, paddingHorizontal: 5, paddingVertical: 2 },
  guestTagText:     { fontSize: 10, fontWeight: '600', color: Arena.text },

  searchWrap:    { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.graphiteElevated, borderRadius: Radius.r8, borderWidth: 1, borderColor: Arena.neonBorder, paddingHorizontal: 10, marginBottom: 8, gap: 6 },
  searchIcon:    { flexShrink: 0 },
  searchInput:   { flex: 1, fontSize: 14, color: Arena.text, paddingVertical: 9 },

  guestFilters:  { backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 10 },
  filterRow:     { flexDirection: 'row', gap: 10, marginBottom: 8 },
  filterLabel:   { fontSize: 11, fontWeight: '600', color: Arena.text, marginBottom: 4 },
  filterInput:   { backgroundColor: Arena.graphiteElevated, borderWidth: 1, borderColor: Arena.neonBorder, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14, color: Arena.text },
  flex1:         { flex: 1 },

  genderRow:         { flexDirection: 'row', gap: 8, marginTop: 4 },
  genderChip:        { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: Radius.r8, borderWidth: 1, borderColor: Arena.line, backgroundColor: Arena.card },
  genderChipActive:  { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  genderChipText:    { fontSize: 12, fontWeight: '500', color: Arena.textMuted },
  genderChipTextActive: { color: Arena.neon, fontWeight: '700' },

  athleteCounter:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Arena.neonSoft, borderRadius: Radius.r12, padding: Spacing.md, marginBottom: 8 },
  athleteCounterLeft:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  athleteCounterNum:   { fontSize: 22, fontWeight: '800', color: Arena.neon },
  athleteCounterLabel: { fontSize: 13, fontWeight: '500', color: Arena.neon },
  athleteCounterSub:   { fontSize: 12, color: Arena.text, fontWeight: '600' },

  guestRow:        { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 6, gap: 10 },
  guestRowSelected: { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  applicationRow:  { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, marginBottom: 6, gap: 10 },
  applicationActions: { flexDirection: 'row', gap: 6 },
  applicationBtn:  { width: 34, height: 34, borderRadius: Radius.r8, alignItems: 'center', justifyContent: 'center' },
  applicationAccept: { backgroundColor: Arena.successBg },
  applicationDecline: { backgroundColor: Arena.errorBg },
  applicationWarning: { fontSize: 11, color: Arena.error, fontWeight: '700', marginTop: 2 },
  selectCircle:    { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center', backgroundColor: Arena.bg },
  selectCircleActive: { borderColor: Arena.neon, backgroundColor: Arena.neon },
  guestAvatar:     { width: 40, height: 40, borderRadius: 20, backgroundColor: Arena.neonSoft, alignItems: 'center', justifyContent: 'center' },
  guestAvatarText: { fontSize: 13, fontWeight: '800', color: Arena.neon },
  guestName:       { fontSize: 13, fontWeight: '600', color: Arena.text },
  guestSub:        { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  ovrBadge:        { borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 4, alignItems: 'center' },
  ovrHigh:         { backgroundColor: Arena.successBg },
  ovrMid:          { backgroundColor: Arena.warningBg },
  ovrLow:          { backgroundColor: Arena.errorBg },
  ovrText:         { fontSize: 12, fontWeight: '800', color: Arena.text },
  favoriteBtn:     { width: 34, height: 34, borderRadius: 17, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, alignItems: 'center', justifyContent: 'center' },
  favoriteBtnActive: { backgroundColor: Arena.warningBg, borderColor: Arena.warningBg },

  paymentCard:     { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, gap: 10 },
  paymentTitle:    { fontSize: 13, fontWeight: '800', color: Arena.text },
  paymentText:     { fontSize: 12, color: Arena.textMuted, marginTop: 2 },
  paymentBtn:      { backgroundColor: Arena.neon, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 9 },
  paymentBtnText:  { color: Arena.bgDeep, fontSize: 12, fontWeight: '900' },
  paymentBadge:    { backgroundColor: Arena.successBg, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 9 },
  paymentBadgeText:{ color: Arena.success, fontSize: 12, fontWeight: '800' },
  paymentReportedBadge: { backgroundColor: Arena.warningBg },
  paymentReportedBadgeText: { color: Arena.warning },

  matchActionsCard: { backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: Spacing.md, gap: 10 },
  inlineActionRow:  { flexDirection: 'row', alignItems: 'center', gap: 8 },
  secondaryActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 10 },
  secondaryActionDone: { backgroundColor: Arena.successBg, borderColor: Arena.successBg },
  secondaryActionDanger: { backgroundColor: Arena.errorBg, borderColor: Arena.errorBg },
  secondaryActionText: { fontSize: 12, fontWeight: '700', color: Arena.text },
  smallPrimaryBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 10 },
  smallPrimaryText: { fontSize: 12, fontWeight: '900', color: Arena.bgDeep },
  recordedScoreText: { fontSize: 15, fontWeight: '700', color: Arena.text, textAlign: 'center', paddingVertical: 8 },
  teamsWrap:       { gap: 8 },
  teamsDiff:       { fontSize: 11, fontWeight: '700', color: Arena.textMuted },
  teamBox:         { backgroundColor: Arena.graphiteElevated, borderRadius: Radius.r8, borderWidth: 1, borderColor: Arena.line, padding: 10 },
  myTeamBox:       { backgroundColor: Arena.neonSoft, borderColor: Arena.neon },
  teamTitle:       { fontSize: 12, fontWeight: '800', color: Arena.text, marginBottom: 4 },
  myTeamTitle:     { color: Arena.neon },
  teamAthlete:     { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  inviteBtn:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Arena.neon, borderRadius: Radius.r12, paddingVertical: 13 },
  inviteBtnDisabled: { opacity: 0.6 },
  inviteBtnText:     { color: Arena.bgDeep, fontSize: 14, fontWeight: '900' },

  adminActionsRow:   { flexDirection: 'row', gap: 10, marginTop: 12 },
  actionBtn:         { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: Radius.r8, paddingVertical: 10 },
  actionBtnCancel:   { backgroundColor: Arena.errorBg, borderWidth: 1, borderColor: Arena.error },
  actionBtnFinish:   { backgroundColor: Arena.successBg, borderWidth: 1, borderColor: Arena.success },
  actionBtnTextCancel: { fontSize: 12, fontWeight: '700', color: Arena.error },
  actionBtnTextFinish: { fontSize: 12, fontWeight: '700', color: Arena.success },

  modalOverlay:      { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end', alignItems: 'center' },
  modal:             { backgroundColor: Arena.graphiteElevated, borderTopLeftRadius: Radius.r16, borderTopRightRadius: Radius.r16, padding: Spacing.lg, width: '100%', maxHeight: '80%' },
  modalTitle:        { fontSize: 16, fontWeight: '800', color: Arena.text, marginBottom: 4 },
  modalSubtitle:     { fontSize: 13, color: Arena.textMuted, marginBottom: 16 },
  modalInput:        { backgroundColor: Arena.card, borderWidth: 1, borderColor: Arena.neonBorder, borderRadius: Radius.r8, paddingHorizontal: 12, paddingVertical: 12, fontSize: 14, color: Arena.text, marginBottom: 8, maxHeight: 120 },
  modalCharCount:    { fontSize: 11, color: Arena.textSubtle, marginBottom: 16, textAlign: 'right' },
  modalButtonRow:    { flexDirection: 'row', gap: 10 },
  modalBtn:          { flex: 1, paddingVertical: 12, borderRadius: Radius.r8, alignItems: 'center', justifyContent: 'center' },
  modalBtnPrimary:   { backgroundColor: Arena.neon },
  modalBtnSecondary: { backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line },
  modalBtnTextPrimary: { color: Arena.bgDeep, fontSize: 14, fontWeight: '900' },
  modalBtnTextSecondary: { color: Arena.text, fontSize: 14, fontWeight: '700' },
  modalBtnDisabled:  { opacity: 0.5 },
});
