import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '../tokens/theme';

export const styles = StyleSheet.create({
  input: {
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Arena.text,
    fontWeight: '700',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.r16,
    paddingVertical: 14,
    paddingHorizontal: Spacing.lg,
  },
  buttonPrimary: {
    backgroundColor: Arena.neon,
  },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: Arena.line,
    backgroundColor: Arena.cardSoft,
  },
  buttonText: {
    backgroundColor: 'transparent',
    paddingVertical: Spacing.md,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  buttonLabel: {
    color: Arena.buttonLabelPrimary,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  buttonSecondaryLabel: {
    color: Arena.text,
  },
  buttonTextLabel: {
    color: Arena.neon,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Arena.bg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
  },
  headerBack: { marginRight: 12 },
  stepInfo: { flex: 1 },
  stepLabel: { fontSize: 12, color: Arena.textMuted, marginBottom: 6 },
  progressBar: { flexDirection: 'row', gap: 6 },
  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: Arena.line },
  progressDotActive: { backgroundColor: Arena.neon },
  field: { marginBottom: 12 },
  fieldLabel: { fontSize: 12, fontWeight: '800', color: Arena.text, marginBottom: 6 },
  chipList: { gap: 8, marginBottom: 12 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radius.r8,
    borderWidth: 1.5,
    borderColor: Arena.line,
    backgroundColor: Arena.card,
  },
  chipActive: { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  chipText: { fontSize: 12, color: Arena.textMuted, fontWeight: '700' },
  chipTextActive: { color: Arena.neon, fontWeight: '900' },
  levelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderRadius: Radius.r12,
    borderWidth: 1.5,
    borderColor: Arena.line,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  levelCardActive: { borderColor: Arena.neon, backgroundColor: Arena.neonSoft },
  levelIcon: { fontSize: 22 },
  levelContent: { flex: 1 },
  levelLabel: { fontSize: 14, fontWeight: '800', color: Arena.text },
  levelLabelActive: { color: Arena.neon },
  levelDesc: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Arena.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: { borderColor: Arena.neon },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Arena.neon },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Arena.card,
    borderRadius: Radius.r12,
    padding: 14,
    borderWidth: 1,
    borderColor: Arena.line,
    marginBottom: 12,
  },
  switchText: { flex: 1 },
  switchLabel: { fontSize: 13, fontWeight: '800', color: Arena.text },
  switchDesc: { fontSize: 11, color: Arena.textMuted, marginTop: 2 },
  selectBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectBtnText: { fontSize: 14, color: Arena.text, fontWeight: '700' },
  selectBtnPlaceholder: { color: Arena.textSubtle },
  selectArrow: { fontSize: 12, color: Arena.neon },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  modalSheet: {
    backgroundColor: Arena.graphiteElevated,
    borderTopLeftRadius: Radius.r16,
    borderTopRightRadius: Radius.r16,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
  },
  modalTitle: { fontSize: 15, fontWeight: '800', color: Arena.text },
  modalClose: { fontSize: 18, color: Arena.textMuted },
  modalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
  },
  modalItemActive: { backgroundColor: Arena.neonSoft },
  modalItemText: { fontSize: 14, color: Arena.text },
  modalItemTextActive: { color: Arena.neon, fontWeight: '900' },
  timeBtnText: { fontSize: 14, color: Arena.text, fontWeight: '700' },
  primaryText: { color: Arena.neon },
});
