import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../tokens/theme';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
  },
  headerBack: { marginRight: 12 },
  stepInfo: { flex: 1 },
  stepLabel: { fontSize: 12, color: Colors.n500, marginBottom: 6 },
  progressBar: { flexDirection: 'row', gap: 6 },
  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: Colors.n200 },
  progressDotActive: { backgroundColor: Colors.primary },
  field: { marginBottom: 12 },
  fieldLabel: { fontSize: 12, fontWeight: '600', color: Colors.n700, marginBottom: 5 },
  chipList: { gap: 8, marginBottom: 12 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radius.r8,
    borderWidth: 1.5,
    borderColor: Colors.n300,
    backgroundColor: Colors.white,
  },
  chipActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  chipText: { fontSize: 12, color: Colors.n700, fontWeight: '500' },
  chipTextActive: { color: Colors.primary, fontWeight: '700' },
  levelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 1.5,
    borderColor: Colors.n200,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  levelCardActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  levelIcon: { fontSize: 22 },
  levelContent: { flex: 1 },
  levelLabel: { fontSize: 14, fontWeight: '700', color: Colors.n900 },
  levelLabelActive: { color: Colors.primary },
  levelDesc: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.n300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: { borderColor: Colors.primary },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.primary },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.n200,
    marginBottom: 12,
  },
  switchText: { flex: 1 },
  switchLabel: { fontSize: 13, fontWeight: '600', color: Colors.n800 },
  switchDesc: { fontSize: 11, color: Colors.n500, marginTop: 2 },
  selectBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectBtnText: { fontSize: 14, color: Colors.n900 },
  selectBtnPlaceholder: { color: Colors.n400 },
  selectArrow: { fontSize: 12, color: Colors.n500 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  modalSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.r16,
    borderTopRightRadius: Radius.r16,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
  },
  modalTitle: { fontSize: 15, fontWeight: '700', color: Colors.n900 },
  modalClose: { fontSize: 18, color: Colors.n500 },
  modalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n100,
  },
  modalItemActive: { backgroundColor: Colors.primaryLight },
  modalItemText: { fontSize: 14, color: Colors.n900 },
  modalItemTextActive: { color: Colors.primary, fontWeight: '700' },
  timeBtnText: { fontSize: 14, color: Colors.n900, fontWeight: '600' },
  primaryText: { color: Colors.primary },
});
