import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../../ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, gap: 12 },
  headerBody: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '700', color: Colors.n900 },
  headerSub: { fontSize: 11, color: Colors.n500 },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, paddingHorizontal: Spacing.lg, paddingVertical: 10, gap: 10 },
  searchInput: { flex: 1, fontSize: 16, color: Colors.n900, paddingVertical: 2 },
  sectionHeader: { paddingHorizontal: Spacing.lg, paddingTop: 16, paddingBottom: 6 },
  sectionTitle: { fontSize: 12, fontWeight: '700', color: Colors.n500, textTransform: 'uppercase', letterSpacing: 0.5 },
  emptyWrap: { alignItems: 'center', paddingTop: 60, paddingHorizontal: 40, gap: 8 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: Colors.n700 },
  emptyText: { fontSize: 13, color: Colors.n500, textAlign: 'center', lineHeight: 20 },
  row: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, paddingHorizontal: Spacing.lg, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.n100, gap: 12 },
  avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  avatarPending: { backgroundColor: Colors.warningLight },
  avatarText: { fontSize: 14, fontWeight: '800', color: Colors.primary },
  avatarTextPending: { color: Colors.warning },
  info: { flex: 1, gap: 3 },
  name: { fontSize: 14, fontWeight: '600', color: Colors.n900 },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  posTag: { backgroundColor: Colors.n100, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  posTagText: { fontSize: 10, fontWeight: '700', color: Colors.n700 },
  overall: { fontSize: 11, color: Colors.n500 },
  email: { fontSize: 11, color: Colors.n400, flexShrink: 1 },
  pendingTag: { backgroundColor: Colors.warningLight, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  pendingTagText: { fontSize: 10, fontWeight: '700', color: Colors.warningDark },
  inviteBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: Colors.primary, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 7, flexShrink: 0 },
  inviteBtnSent: { backgroundColor: Colors.successLight },
  inviteBtnError: { backgroundColor: Colors.errorLight },
  inviteBtnText: { fontSize: 12, fontWeight: '700', color: Colors.white },
  inviteBtnTextSent: { color: Colors.success },
  inviteBtnTextError: { color: Colors.error },
  resendBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.n100, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 7, flexShrink: 0 },
  resendBtnSent: { backgroundColor: Colors.successLight },
  resendBtnText: { fontSize: 12, fontWeight: '600', color: Colors.n700 },
  resendBtnTextSent: { color: Colors.success },
});
