import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  keyboard: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Arena.bg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Arena.cardSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: { flex: 1 },
  headerTitle: { fontSize: 15, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 11, color: Arena.textMuted },
  dots: { flexDirection: 'row', gap: 5 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Arena.line },
  dotActive: { backgroundColor: Arena.neon },
  scroll: { padding: Spacing.lg, paddingBottom: 40 },
  stepTitle: { fontSize: 18, fontWeight: '800', color: Arena.text, marginBottom: 2 },
  stepSub: { fontSize: 12, color: Arena.textMuted, marginBottom: 20 },
  btn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Arena.neon,
    borderRadius: Radius.r16,
    paddingVertical: 15,
    marginTop: 16,
  },
  btnText: { color: Arena.bgDeep, fontSize: 15, fontWeight: '900' },
  inviteContainer: { flex: 1 },
  chipsWrap: {
    backgroundColor: Arena.bg,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    paddingVertical: 10,
  },
  chipsScroll: { paddingHorizontal: Spacing.lg },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Arena.neonSoft,
    borderRadius: Radius.r999,
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 10,
    gap: 6,
    maxWidth: 130,
    marginRight: 8,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
  },
  chipAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Arena.neon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipAvatarText: { fontSize: 9, fontWeight: '800', color: Arena.bgDeep },
  chipName: { flex: 1, fontSize: 12, fontWeight: '800', color: Arena.neon },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Arena.graphiteElevated,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 10,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 15, color: Arena.text, fontWeight: '700' },
  emptyList: { flexGrow: 1 },
  resultsList: { paddingBottom: 100 },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 60, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textSubtle },
  athleteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
    backgroundColor: Arena.bg,
  },
  athleteRowSelected: { backgroundColor: Arena.mossSoft },
  athleteAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Arena.graphiteElevated,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Arena.line,
  },
  athleteAvatarText: { fontSize: 14, fontWeight: '800', color: Arena.textMuted },
  athleteBody: { flex: 1 },
  athleteName: { fontSize: 14, fontWeight: '800', color: Arena.text },
  athleteMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  posTag: { backgroundColor: Arena.cardSoft, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  posTagText: { fontSize: 10, fontWeight: '700', color: Arena.textMuted },
  athleteOverall: { fontSize: 11, color: Arena.textSubtle },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: Arena.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleActive: { backgroundColor: Arena.neon, borderColor: Arena.neon },
  actionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Arena.graphiteElevated,
    borderTopWidth: 1,
    borderTopColor: Arena.line,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
    gap: 12,
  },
  actionInfo: { flex: 1 },
  actionCount: { fontSize: 13, fontWeight: '800', color: Arena.text },
  actionHint: { fontSize: 11, color: Arena.textMuted },
  actionBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r16, paddingHorizontal: 20, paddingVertical: 12 },
  actionBtnDisabled: { opacity: 0.7 },
  actionBtnText: { color: Arena.bgDeep, fontWeight: '900', fontSize: 14 },
});
