import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../../ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  keyboard: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.n100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: { flex: 1 },
  headerTitle: { fontSize: 15, fontWeight: '700', color: Colors.n900 },
  headerSub: { fontSize: 11, color: Colors.n500 },
  dots: { flexDirection: 'row', gap: 5 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.n200 },
  dotActive: { backgroundColor: Colors.primary },
  scroll: { padding: Spacing.lg, paddingBottom: 40 },
  stepTitle: { fontSize: 18, fontWeight: '800', color: Colors.n900, marginBottom: 2 },
  stepSub: { fontSize: 12, color: Colors.n500, marginBottom: 20 },
  btn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: Radius.r12,
    paddingVertical: 15,
    marginTop: 16,
  },
  btnText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  inviteContainer: { flex: 1 },
  chipsWrap: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    paddingVertical: 10,
  },
  chipsScroll: { paddingHorizontal: Spacing.lg },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primaryLight,
    borderRadius: Radius.r999,
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 10,
    gap: 6,
    maxWidth: 130,
    marginRight: 8,
  },
  chipAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipAvatarText: { fontSize: 9, fontWeight: '800', color: Colors.white },
  chipName: { flex: 1, fontSize: 12, fontWeight: '600', color: Colors.primary },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 10,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 15, color: Colors.n900 },
  emptyList: { flexGrow: 1 },
  resultsList: { paddingBottom: 100 },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 60, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  athleteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n100,
    gap: 12,
    backgroundColor: Colors.white,
  },
  athleteRowSelected: { backgroundColor: Colors.primaryLight },
  athleteAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.n200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  athleteAvatarText: { fontSize: 14, fontWeight: '800', color: Colors.n700 },
  athleteBody: { flex: 1 },
  athleteName: { fontSize: 14, fontWeight: '600', color: Colors.n900 },
  athleteMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  posTag: { backgroundColor: Colors.n100, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  posTagText: { fontSize: 10, fontWeight: '700', color: Colors.n700 },
  athleteOverall: { fontSize: 11, color: Colors.n500 },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: Colors.n300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  actionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.n200,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
    gap: 12,
  },
  actionInfo: { flex: 1 },
  actionCount: { fontSize: 13, fontWeight: '700', color: Colors.n900 },
  actionHint: { fontSize: 11, color: Colors.n500 },
  actionBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r12, paddingHorizontal: 20, paddingVertical: 12 },
  actionBtnDisabled: { opacity: 0.7 },
  actionBtnText: { color: Colors.white, fontWeight: '700', fontSize: 14 },
});
