import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  field: { marginBottom: 12 },
  fieldLabel: { fontSize: 12, fontWeight: '600', color: Colors.n700, marginBottom: 5 },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputText: { flex: 1, fontSize: 14, color: Colors.n900 },
  selectBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.n300,
    borderRadius: Radius.r8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectBtnText: { fontSize: 14, color: Colors.n900 },
  selectBtnPlaceholder: { color: Colors.n400 },
  selectArrow: { fontSize: 12, color: Colors.n500 },
  timeBtnText: { fontSize: 14, color: Colors.n900, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  modalSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.r16,
    borderTopRightRadius: Radius.r16,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
  },
  modalTitle: { fontSize: 15, fontWeight: '700', color: Colors.n900 },
  modalClose: { fontSize: 18, color: Colors.n500 },
  modalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n100,
  },
  modalItemActive: { backgroundColor: Colors.primaryLight },
  modalItemText: { fontSize: 14, color: Colors.n900 },
  modalItemTextActive: { color: Colors.primary, fontWeight: '700' },
  primaryText: { color: Colors.primary },
});
