import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Arena.bg,
  },
  center: {
    alignItems: 'center',
    gap: Spacing.md,
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  loadingHeader: {
    left: Spacing.lg,
    position: 'absolute',
    top: Spacing.md,
  },
  header: {
    alignItems: 'center',
    backgroundColor: Arena.bg,
    borderBottomColor: Arena.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  headerTitle: {
    color: Arena.text,
    fontSize: 16,
    fontWeight: '800',
  },
  headerSpacer: {
    width: 40,
  },
  content: {
    padding: Spacing.lg,
    paddingBottom: Spacing.xxl,
    gap: Spacing.md,
  },
  scoreCard: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r16,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.lg,
  },
  finalResultCard: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r16,
    borderWidth: 1,
    gap: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xl,
  },
  finalResultLabel: {
    color: Arena.text,
    fontSize: 16,
    fontWeight: '800',
  },
  finalResultMeta: {
    color: Arena.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  liveLabel: {
    color: Colors.error,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: Spacing.sm,
  },
  clock: {
    color: Arena.textMuted,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: Spacing.md,
  },
  scoreRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.md,
    justifyContent: 'center',
    width: '100%',
  },
  teamName: {
    color: Arena.text,
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  score: {
    color: Arena.text,
    fontSize: 32,
    fontWeight: '800',
  },
  sponsorCard: {
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    padding: Spacing.md,
  },
  sponsorCaption: {
    color: Arena.textSubtle,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: Spacing.sm,
    textTransform: 'uppercase',
  },
  sponsorContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.md,
  },
  sponsorLogo: {
    backgroundColor: Arena.cardSoft,
    borderRadius: Radius.r8,
    height: 52,
    width: 72,
  },
  sponsorName: {
    color: Arena.text,
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
  },
  lineup: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  teamColumn: {
    flex: 1,
    gap: Spacing.xs,
  },
  teamHeading: {
    alignItems: 'center',
    borderRadius: Radius.r8,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  homeHeading: {
    backgroundColor: Colors.successLight,
  },
  awayHeading: {
    backgroundColor: Arena.graphite,
  },
  teamHeadingText: {
    color: Arena.text,
    fontSize: 13,
    fontWeight: '800',
  },
  awayHeadingText: {
    color: Arena.text,
  },
  emptyLineup: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    paddingVertical: Spacing.lg,
  },
  emptyLineupText: {
    color: Arena.textMuted,
    fontSize: 12,
  },
  playerCard: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.sm,
    minHeight: 48,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  playerCardInteractive: {
    borderColor: Arena.neon,
    borderWidth: 1.5,
  },
  playerCardDisabled: {
    opacity: 0.55,
  },
  playerName: {
    color: Arena.text,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  playerAvatar: {
    backgroundColor: Arena.cardSoft,
    borderRadius: Radius.r999,
    height: 32,
    width: 32,
  },
  actions: {
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    gap: Spacing.md,
    padding: Spacing.md,
  },
  sectionTitle: {
    color: Arena.text,
    fontSize: 16,
    fontWeight: '800',
  },
  timeline: {
    gap: Spacing.sm,
  },
  emptyTimeline: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    paddingVertical: Spacing.xl,
  },
  emptyText: {
    color: Arena.textMuted,
    fontSize: 13,
  },
  eventRow: {
    alignItems: 'center',
    backgroundColor: Arena.card,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: Spacing.md,
    padding: Spacing.md,
  },
  minuteBadge: {
    alignItems: 'center',
    backgroundColor: Colors.primaryLight,
    borderRadius: Radius.r999,
    justifyContent: 'center',
    minWidth: 48,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  minuteText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  eventContent: {
    flex: 1,
  },
  eventTitle: {
    color: Arena.text,
    fontSize: 14,
    fontWeight: '700',
  },
  eventSubtitle: {
    color: Arena.textMuted,
    fontSize: 12,
    marginTop: Spacing.xs,
  },
});
