import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center', gap: 10, padding: 24 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Arena.graphiteElevated, borderBottomWidth: 1, borderBottomColor: Arena.line, gap: 12 },
  headerBody: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 12, color: Arena.textMuted, marginTop: 1 },
  errorText: { fontSize: 14, color: Arena.textMuted },
  primaryBtn: { backgroundColor: Arena.neon, paddingHorizontal: 18, paddingVertical: 10, borderRadius: Radius.r8 },
  primaryBtnText: { color: Arena.buttonLabelPrimary, fontWeight: '900' },
  scrollContent: { paddingBottom: 88 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  metricCard: { width: '48%', borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, backgroundColor: Arena.card, padding: 12 },
  metricLabel: { fontSize: 11, color: Arena.textSubtle, marginBottom: 6 },
  metricValue: { fontSize: 17, fontWeight: '900' },
  filterBlock: { paddingHorizontal: Spacing.lg, gap: 8 },
  filterTitle: { fontSize: 12, fontWeight: '800', color: Arena.text },
  section: { paddingHorizontal: Spacing.lg, gap: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '900', color: Arena.text, marginBottom: 2 },
  sectionTitleSpaced: { marginTop: 18 },
  listSeparator: { height: 8 },
  rowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: 12, gap: 10 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 13, fontWeight: '800', color: Arena.text },
  rowSub: { fontSize: 11, color: Arena.textMuted, marginTop: 3 },
  amounts: { alignItems: 'flex-end', maxWidth: 132 },
  amountText: { fontSize: 13, fontWeight: '900', color: Arena.text },
  statusText: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  paidText: { fontSize: 13, fontWeight: '900', color: Arena.success },
  pendingText: { fontSize: 11, fontWeight: '700', color: Arena.warning, marginTop: 2 },
  overdueText: { fontSize: 11, fontWeight: '700', color: Arena.error, marginTop: 2 },
  reportedText: { fontSize: 11, fontWeight: '700', color: Arena.warning, marginTop: 4 },
  payBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 6, marginTop: 6 },
  payBtnText: { color: Arena.buttonLabelPrimary, fontSize: 11, fontWeight: '900' },
  paidBadge: { backgroundColor: Arena.successBg, borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 5 },
  paidBadgeFull: { alignItems: 'center', backgroundColor: Arena.successBg, borderRadius: Radius.r12, paddingVertical: 12, marginTop: 4 },
  paidBadgeText: { color: Arena.success, fontSize: 12, fontWeight: '800' },
  reportedBadgeFull: { alignItems: 'center', backgroundColor: Arena.warningBg, borderRadius: Radius.r12, paddingVertical: 12, marginTop: 4 },
  reportedBadgeText: { color: Arena.warning, fontSize: 12, fontWeight: '800' },
  emptyCard: { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textMuted },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: Arena.graphiteElevated, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, padding: Spacing.lg, gap: 10 },
  modalHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Arena.line, alignSelf: 'center', marginBottom: 8 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: Arena.text, marginBottom: 4 },
  infoLine: { borderWidth: 1, borderColor: Arena.line, borderRadius: Radius.r12, padding: 10, backgroundColor: Arena.card },
  infoLabel: { fontSize: 11, color: Arena.textSubtle, marginBottom: 3 },
  infoValue: { fontSize: 13, fontWeight: '700', color: Arena.text },
  infoValueStrong: { color: Arena.neon, fontSize: 15 },
  primaryBtnFull: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Arena.neon, borderRadius: Radius.r12, paddingVertical: 13, marginTop: 4 },
  primaryBtnFullDisabled: { opacity: 0.6 },
  secondaryBtnFull: { alignItems: 'center', backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, borderRadius: Radius.r12, paddingVertical: 13 },
  secondaryBtnText: { color: Arena.text, fontWeight: '800' },
});
