import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center', gap: 10, padding: 24 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.n200, gap: 12 },
  headerBody: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSub: { fontSize: 12, color: Colors.n500, marginTop: 1 },
  errorText: { fontSize: 14, color: Colors.n700 },
  primaryBtn: { backgroundColor: Colors.primary, paddingHorizontal: 18, paddingVertical: 10, borderRadius: Radius.r8 },
  primaryBtnText: { color: Colors.white, fontWeight: '800' },
  scrollContent: { paddingBottom: 88 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  metricCard: { width: '48%', borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 12 },
  metricLabel: { fontSize: 11, color: Colors.n500, marginBottom: 6 },
  metricValue: { fontSize: 17, fontWeight: '900' },
  filterBlock: { paddingHorizontal: Spacing.lg, gap: 8 },
  filterTitle: { fontSize: 12, fontWeight: '800', color: Colors.n700 },
  chips: { gap: 8, paddingRight: Spacing.lg },
  chip: { borderRadius: Radius.r999, borderWidth: 1, borderColor: Colors.n200, backgroundColor: Colors.white, paddingHorizontal: 12, paddingVertical: 7 },
  chipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  chipText: { fontSize: 12, fontWeight: '700', color: Colors.n600 },
  chipTextActive: { color: Colors.white },
  tabs: { flexDirection: 'row', margin: Spacing.lg, backgroundColor: Colors.n100, borderRadius: Radius.r12, padding: 4 },
  tabBtn: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: Radius.r8 },
  tabBtnActive: { backgroundColor: Colors.white },
  tabText: { fontSize: 12, fontWeight: '700', color: Colors.n500 },
  tabTextActive: { color: Colors.primary },
  section: { paddingHorizontal: Spacing.lg, gap: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '900', color: Colors.n900, marginBottom: 2 },
  sectionTitleSpaced: { marginTop: 18 },
  listSeparator: { height: 8 },
  rowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 12, gap: 10 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 13, fontWeight: '800', color: Colors.n900 },
  rowSub: { fontSize: 11, color: Colors.n500, marginTop: 3 },
  amounts: { alignItems: 'flex-end', maxWidth: 132 },
  amountText: { fontSize: 13, fontWeight: '900', color: Colors.n900 },
  statusText: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  paidText: { fontSize: 13, fontWeight: '900', color: Colors.successDark },
  pendingText: { fontSize: 11, fontWeight: '700', color: Colors.warningDark, marginTop: 2 },
  overdueText: { fontSize: 11, fontWeight: '700', color: Colors.errorDark, marginTop: 2 },
  reportedText: { fontSize: 11, fontWeight: '700', color: Colors.warningDark, marginTop: 4 },
  payBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 6, marginTop: 6 },
  payBtnText: { color: Colors.white, fontSize: 11, fontWeight: '800' },
  paidBadge: { backgroundColor: Colors.successLight, borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 5 },
  paidBadgeFull: { alignItems: 'center', backgroundColor: Colors.successLight, borderRadius: Radius.r12, paddingVertical: 12, marginTop: 4 },
  paidBadgeText: { color: Colors.successDark, fontSize: 12, fontWeight: '800' },
  reportedBadgeFull: { alignItems: 'center', backgroundColor: Colors.warningLight, borderRadius: Radius.r12, paddingVertical: 12, marginTop: 4 },
  reportedBadgeText: { color: Colors.warningDark, fontSize: 12, fontWeight: '800' },
  emptyCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: Colors.white, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, padding: Spacing.lg, gap: 10 },
  modalHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Colors.n300, alignSelf: 'center', marginBottom: 8 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: Colors.n900, marginBottom: 4 },
  infoLine: { borderWidth: 1, borderColor: Colors.n200, borderRadius: Radius.r12, padding: 10, backgroundColor: Colors.n50 },
  infoLabel: { fontSize: 11, color: Colors.n500, marginBottom: 3 },
  infoValue: { fontSize: 13, fontWeight: '700', color: Colors.n800 },
  infoValueStrong: { color: Colors.primary, fontSize: 15 },
  primaryBtnFull: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Colors.primary, borderRadius: Radius.r12, paddingVertical: 13, marginTop: 4 },
  primaryBtnFullDisabled: { opacity: 0.6 },
  secondaryBtnFull: { alignItems: 'center', backgroundColor: Colors.n100, borderRadius: Radius.r12, paddingVertical: 13 },
  secondaryBtnText: { color: Colors.n700, fontWeight: '800' },
});
