import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '@ui/tokens/theme';

const neon = '#D7FF45';
const field = '#121A1B';
const fieldBorder = 'rgba(215, 255, 69, 0.16)';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#06100F',
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#06100F',
    overflow: 'hidden',
  },
  fieldGlowTop: {
    position: 'absolute',
    top: -180,
    right: -120,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(37, 85, 98, 0.42)',
  },
  fieldGlowBottom: {
    position: 'absolute',
    bottom: -130,
    left: -90,
    width: 330,
    height: 330,
    borderRadius: 165,
    backgroundColor: 'rgba(59, 96, 43, 0.38)',
  },
  pitchLineVertical: {
    position: 'absolute',
    top: 88,
    bottom: -30,
    left: '18%',
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.055)',
    transform: [{ rotate: '-12deg' }],
  },
  pitchLineHorizontal: {
    position: 'absolute',
    top: '46%',
    left: -36,
    right: -36,
    height: 1,
    backgroundColor: 'rgba(215, 255, 69, 0.08)',
    transform: [{ rotate: '-8deg' }],
  },
  pitchCircle: {
    position: 'absolute',
    top: '22%',
    right: -110,
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.055)',
  },
  dust: {
    position: 'absolute',
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: 'rgba(215, 255, 69, 0.08)',
  },
  dustA: {
    top: '18%',
    right: '18%',
  },
  dustB: {
    bottom: '24%',
    left: '9%',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  keyboard: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.xl,
    paddingTop: 24,
    paddingBottom: 28,
  },
  hero: {
    gap: 34,
    paddingTop: 8,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  logoMark: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    borderRadius: Radius.r999,
    borderWidth: 1,
    borderColor: 'rgba(215, 255, 69, 0.46)',
    backgroundColor: 'rgba(215, 255, 69, 0.08)',
    shadowColor: neon,
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  logoCheck: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    alignItems: 'center',
    justifyContent: 'center',
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: neon,
  },
  brandName: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  copyBlock: {
    gap: 12,
    maxWidth: 380,
  },
  headline: {
    color: Colors.white,
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 39,
  },
  headlineAccent: {
    color: neon,
    textShadowColor: 'rgba(215, 255, 69, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.82)',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 23,
  },
  form: {
    gap: Spacing.md,
    paddingTop: 18,
  },
  fieldGroup: {
    gap: 8,
  },
  labelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: '800',
  },
  forgotLink: {
    color: 'rgba(215, 255, 69, 0.86)',
    fontSize: 12,
    fontWeight: '800',
  },
  inputShell: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 56,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: fieldBorder,
    backgroundColor: field,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: Colors.white,
    fontSize: 15,
    fontWeight: '700',
    paddingVertical: 0,
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 58,
    borderRadius: Radius.r16,
    backgroundColor: neon,
    marginTop: Spacing.sm,
    shadowColor: neon,
    shadowOpacity: 0.52,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
  },
  btnDisabled: {
    opacity: 0.72,
  },
  primaryButtonText: {
    color: '#07110D',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  dividerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: Spacing.sm,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  dividerText: {
    color: 'rgba(255, 255, 255, 0.68)',
    fontSize: 12,
    fontWeight: '700',
  },
  socialRow: {
    flexDirection: 'row',
    gap: 12,
  },
  socialButton: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minHeight: 50,
    borderRadius: Radius.r16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    flexDirection: 'row',
    gap: 8,
  },
  socialText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  registerLink: {
    alignItems: 'center',
    marginTop: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  registerLinkText: {
    color: 'rgba(255, 255, 255, 0.82)',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  registerLinkHighlight: {
    color: neon,
    fontWeight: '900',
  },
});
