import { StyleSheet } from 'react-native';
import { Arena, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Arena.graphiteElevated,
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
  },
  headerBody: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 11, color: Arena.textMuted, marginTop: 1 },
  searchWrap: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    backgroundColor: Arena.bg,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Arena.graphiteElevated,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    borderRadius: Radius.r16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  searchInput: { flex: 1, fontSize: 15, color: Arena.text, paddingVertical: 1 },
  listContent: { paddingBottom: 28 },
  sectionHeader: { paddingHorizontal: Spacing.lg, paddingTop: 14, paddingBottom: 8 },
  sectionTitle: { fontSize: 12, fontWeight: '900', color: Arena.textMuted, textTransform: 'uppercase', letterSpacing: 0 },
  emptyWrap: {
    alignItems: 'center',
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    paddingVertical: 28,
    paddingHorizontal: Spacing.lg,
    backgroundColor: Arena.card,
    borderWidth: 1,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    gap: 8,
  },
  emptyIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Arena.cardSoft,
    borderWidth: 1,
    borderColor: Arena.line,
  },
  emptyTitle: { fontSize: 15, fontWeight: '900', color: Arena.text },
  emptyText: { fontSize: 13, color: Arena.textMuted, textAlign: 'center', lineHeight: 19 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: Spacing.lg,
    marginBottom: 10,
    backgroundColor: Arena.card,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: Arena.line,
    borderRadius: Radius.r12,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Arena.neonSoft,
    borderWidth: 1,
    borderColor: Arena.neonBorder,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarPending: { backgroundColor: Arena.warningBg, borderColor: Arena.warningBg },
  avatarText: { fontSize: 14, fontWeight: '900', color: Arena.neon },
  avatarTextPending: { color: Arena.warning },
  info: { flex: 1, minWidth: 0, gap: 5 },
  name: { fontSize: 14, fontWeight: '800', color: Arena.text },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  posTag: { backgroundColor: Arena.cardSoft, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  posTagText: { fontSize: 10, fontWeight: '800', color: Arena.text },
  overall: { fontSize: 11, fontWeight: '700', color: Arena.textMuted },
  email: { fontSize: 11, color: Arena.textSubtle, flexShrink: 1 },
  pendingTag: { backgroundColor: Arena.warningBg, borderRadius: Radius.r4, paddingHorizontal: 6, paddingVertical: 2 },
  pendingTagText: { fontSize: 10, fontWeight: '800', color: Arena.warning },
  inviteBtn: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: Arena.neon,
    borderRadius: Radius.r8,
    paddingHorizontal: 11,
    paddingVertical: 8,
    flexShrink: 0,
  },
  inviteBtnSent: { backgroundColor: Arena.successBg, borderWidth: 1, borderColor: Arena.successBg },
  inviteBtnError: { backgroundColor: Arena.errorBg, borderWidth: 1, borderColor: Arena.errorBg },
  inviteBtnText: { fontSize: 12, fontWeight: '900', color: Arena.buttonLabelPrimary },
  inviteBtnTextSent: { color: Arena.success },
  inviteBtnTextError: { color: Arena.error },
  resendBtn: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: Arena.cardSoft,
    borderWidth: 1,
    borderColor: Arena.line,
    borderRadius: Radius.r8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexShrink: 0,
  },
  resendBtnSent: { backgroundColor: Arena.successBg, borderColor: Arena.successBg },
  resendBtnText: { fontSize: 12, fontWeight: '800', color: Arena.text },
  resendBtnTextSent: { color: Arena.success },
});
