import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center' },
  scroll: { padding: Spacing.lg, paddingBottom: 88, gap: 12 },
  heroCard: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.neonBorder, alignItems: 'center', paddingVertical: 28, paddingHorizontal: Spacing.lg, gap: 6 },
  editBtn: { position: 'absolute', top: 12, right: 12, width: 34, height: 34, borderRadius: 17, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: Arena.neonSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  avatarText: { fontSize: 26, fontWeight: '900', color: Arena.neon },
  name: { fontSize: 21, fontWeight: '900', color: Arena.text },
  positionText: { fontSize: 13, color: Arena.textMuted, fontWeight: '700' },
  heroRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  ovrBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: Radius.r999, paddingHorizontal: 14, paddingVertical: 6 },
  ovrNum: { fontSize: 18, fontWeight: '800', color: Colors.white },
  ovrLbl: { fontSize: 11, fontWeight: '600', color: Colors.white },
  statusBadge: { borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 6 },
  statusText: { fontSize: 12, fontWeight: '700' },
  planBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: Radius.r999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  planBadgePremium: { backgroundColor: Arena.neon, borderColor: Arena.neon },
  planBadgeFree: { backgroundColor: Arena.cardSoft, borderColor: Arena.line },
  planText: { fontSize: 12, fontWeight: '800' },
  planTextPremium: { color: Arena.buttonLabelPrimary },
  planTextFree: { color: Arena.textSubtle },
  rankingCard: { minHeight: 76, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.neonBorder, backgroundColor: Arena.neonSoft, padding: Spacing.lg, flexDirection: 'row', alignItems: 'center', gap: 12 },
  rankingIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: Arena.neon, alignItems: 'center', justifyContent: 'center' },
  rankingInfo: { flex: 1, minWidth: 0 },
  rankingTitle: { fontSize: 20, fontWeight: '900', color: Arena.text },
  rankingMeta: { fontSize: 13, fontWeight: '800', color: Arena.textMuted, marginTop: 3 },
  rankingGlow: { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  card: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.line, padding: Spacing.lg },
  cardTitle: { fontSize: 13, fontWeight: '900', color: Arena.text, marginBottom: 14 },
  attrRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  attrLabel: { fontSize: 12, color: Arena.textMuted, width: 80 },
  attrBarBg: { flex: 1, height: 6, backgroundColor: Arena.line, borderRadius: Radius.r999, overflow: 'hidden' },
  attrBarFill: { height: 6, borderRadius: Radius.r999 },
  attrVal: { fontSize: 12, fontWeight: '900', color: Arena.text, width: 26, textAlign: 'right' },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 4 },
  actionLabel: { flex: 1, fontSize: 14, fontWeight: '800', color: Arena.text },
  actionLabelDanger: { color: Colors.error },
  divider: { height: 0.5, backgroundColor: Arena.line, marginVertical: 12 },
});
