import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center' },
  scroll: { padding: Spacing.lg, paddingBottom: 88, gap: 12 },
  heroCard: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.neonBorder, alignItems: 'center', paddingVertical: 28, paddingHorizontal: Spacing.lg, gap: 6 },
  editBtn: { position: 'absolute', top: 12, right: 12, width: 34, height: 34, borderRadius: 17, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: Arena.neonSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  avatarText: { fontSize: 26, fontWeight: '900', color: Arena.neon },
  name: { fontSize: 21, fontWeight: '900', color: Arena.text },
  positionText: { fontSize: 13, color: Arena.textMuted, fontWeight: '700' },
  heroRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  ovrBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: Radius.r999, paddingHorizontal: 14, paddingVertical: 6 },
  ovrNum: { fontSize: 18, fontWeight: '800', color: Colors.white },
  ovrLbl: { fontSize: 11, fontWeight: '600', color: Colors.white },
  statusBadge: { borderRadius: Radius.r999, paddingHorizontal: 12, paddingVertical: 6 },
  statusText: { fontSize: 12, fontWeight: '700' },
  planBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: Radius.r999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  planBadgePremium: { backgroundColor: Arena.neon, borderColor: Arena.neon },
  planBadgeFree: { backgroundColor: Arena.cardSoft, borderColor: Arena.line },
  planText: { fontSize: 12, fontWeight: '800' },
  planTextPremium: { color: Arena.buttonLabelPrimary },
  planTextFree: { color: Arena.textSubtle },
  rankingCard: { minHeight: 76, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.neonBorder, backgroundColor: Arena.neonSoft, padding: Spacing.lg, flexDirection: 'row', alignItems: 'center', gap: 12 },
  rankingIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: Arena.neon, alignItems: 'center', justifyContent: 'center' },
  rankingInfo: { flex: 1, minWidth: 0 },
  rankingTitle: { fontSize: 20, fontWeight: '900', color: Arena.text },
  rankingMeta: { fontSize: 13, fontWeight: '800', color: Arena.textMuted, marginTop: 3 },
  rankingGlow: { width: 36, height: 36, borderRadius: 18, backgroundColor: Arena.cardSoft, alignItems: 'center', justifyContent: 'center' },
  card: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.line, padding: Spacing.lg },
  cardTitle: { fontSize: 13, fontWeight: '900', color: Arena.text, marginBottom: 14 },
  attrRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  attrLabel: { fontSize: 12, color: Arena.textMuted, width: 80 },
  attrBarBg: { flex: 1, height: 6, backgroundColor: Arena.line, borderRadius: Radius.r999, overflow: 'hidden' },
  attrBarFill: { height: 6, borderRadius: Radius.r999 },
  attrVal: { fontSize: 12, fontWeight: '900', color: Arena.text, width: 26, textAlign: 'right' },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 4 },
  actionLabel: { flex: 1, fontSize: 14, fontWeight: '800', color: Arena.text },
  actionLabelDanger: { color: Colors.error },
  divider: { height: 0.5, backgroundColor: Arena.line, marginVertical: 12 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.66)', justifyContent: 'center', padding: Spacing.lg },
  modalCard: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.line, padding: Spacing.lg, gap: 12 },
  modalIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: Colors.error, alignItems: 'center', justifyContent: 'center' },
  modalTitle: { fontSize: 20, fontWeight: '900', color: Arena.text },
  modalDescription: { fontSize: 14, lineHeight: 20, fontWeight: '600', color: Arena.textMuted },
  modalHint: { fontSize: 13, fontWeight: '800', color: Arena.text },
  modalInput: { minHeight: 46, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, backgroundColor: Arena.cardSoft, color: Arena.text, paddingHorizontal: 12, fontSize: 16, fontWeight: '900' },
  modalActions: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  modalButton: { flex: 1, minHeight: 44, borderRadius: Radius.r12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  modalCancelButton: { backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line },
  modalDeleteButton: { backgroundColor: Colors.error },
  modalButtonDisabled: { opacity: 0.45 },
  modalCancelText: { fontSize: 14, fontWeight: '900', color: Arena.text },
  modalDeleteText: { fontSize: 14, fontWeight: '900', color: Arena.buttonLabelPrimary },
  
  // Promotion card styles
  promotionCard: { backgroundColor: Arena.card, borderRadius: Radius.r16, borderWidth: 1, borderColor: Arena.line, padding: Spacing.lg, gap: 8 },
  promotionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  promotionTitle: { fontSize: 15, fontWeight: '900', color: Arena.text, flex: 1 },
  promotionDescription: { fontSize: 13, color: Arena.textMuted, lineHeight: 18, marginBottom: 8 },
  promotionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 46, borderRadius: Radius.r12, backgroundColor: Arena.neon, padding: 12 },
  promotionBtnText: { fontSize: 14, fontWeight: '900', color: Arena.buttonLabelPrimary },
  promotionBtnDisabled: { backgroundColor: Arena.cardSoft, borderColor: Arena.line, borderWidth: 1 },
  promotionBtnTextDisabled: { color: Arena.textSubtle },
  promotionStatusBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Arena.neonSoft, paddingHorizontal: 12, paddingVertical: 8, borderRadius: Radius.r8, marginTop: 4 },
  promotionStatusText: { fontSize: 12, fontWeight: '800', color: Arena.neon },
  promotionLockedBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Arena.cardSoft, paddingHorizontal: 12, paddingVertical: 8, borderRadius: Radius.r8, marginTop: 4 },
  promotionLockedText: { fontSize: 12, fontWeight: '800', color: Arena.textSubtle },
  
  // Ad simulator styles
  adBackdrop: { flex: 1, backgroundColor: 'black', justifyContent: 'center', alignItems: 'center', gap: 20 },
  adTitle: { fontSize: 18, color: Colors.white, fontWeight: '800', textAlign: 'center' },
  adCountdownCircle: { width: 80, height: 80, borderRadius: 40, backgroundColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: Arena.neon },
  adCountdownText: { fontSize: 36, fontWeight: '900', color: Arena.neon },
  adHint: { fontSize: 12, color: 'rgba(255,255,255,0.4)', textAlign: 'center' }
});
