import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.n50 },
  center: { justifyContent: 'center', alignItems: 'center', gap: 10, padding: 24 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.n200,
    gap: 12,
  },
  headerBody: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Colors.n900 },
  headerSub: { fontSize: 12, color: Colors.n500, marginTop: 1 },
  errorText: { fontSize: 14, color: Colors.n700 },
  primaryBtn: { backgroundColor: Colors.primary, paddingHorizontal: 18, paddingVertical: 10, borderRadius: Radius.r8 },
  primaryBtnText: { color: Colors.white, fontWeight: '700' },
  scrollContent: { paddingBottom: 32 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  metricCard: { width: '48%', borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 12 },
  metricLabel: { fontSize: 11, color: Colors.n500, marginBottom: 6 },
  metricValue: { fontSize: 17, fontWeight: '900' },
  actions: { flexDirection: 'row', gap: 10, paddingHorizontal: Spacing.lg, paddingBottom: Spacing.md },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Colors.n200,
    paddingVertical: 12,
  },
  actionText: { fontSize: 12, fontWeight: '800', color: Colors.primary },
  filterBlock: { paddingHorizontal: Spacing.lg, gap: 8 },
  filterTitle: { fontSize: 12, fontWeight: '800', color: Colors.n700 },
  chips: { gap: 8, paddingRight: Spacing.lg },
  chip: { borderRadius: Radius.r999, borderWidth: 1, borderColor: Colors.n200, backgroundColor: Colors.white, paddingHorizontal: 12, paddingVertical: 7 },
  chipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  chipText: { fontSize: 12, fontWeight: '700', color: Colors.n600 },
  chipTextActive: { color: Colors.white },
  tabs: { flexDirection: 'row', margin: Spacing.lg, backgroundColor: Colors.n100, borderRadius: Radius.r12, padding: 4 },
  tabBtn: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: Radius.r8 },
  tabBtnActive: { backgroundColor: Colors.white },
  tabText: { fontSize: 10, fontWeight: '700', color: Colors.n500 },
  tabTextActive: { color: Colors.primary },
  section: { paddingHorizontal: Spacing.lg, gap: 8 },
  listSeparator: { height: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '900', color: Colors.n900, marginBottom: 2 },
  sectionTitleSpaced: { marginTop: 18 },
  rowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 12, gap: 10 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 13, fontWeight: '800', color: Colors.n900 },
  rowSub: { fontSize: 11, color: Colors.n500, marginTop: 3 },
  amounts: { alignItems: 'flex-end', maxWidth: 132 },
  paidText: { fontSize: 13, fontWeight: '900', color: Colors.successDark },
  pendingText: { fontSize: 11, fontWeight: '700', color: Colors.warningDark, marginTop: 2 },
  overdueText: { fontSize: 11, fontWeight: '700', color: Colors.errorDark, marginTop: 2 },
  amountText: { fontSize: 13, fontWeight: '900', color: Colors.n900 },
  expenseText: { color: Colors.errorDark },
  expenseValue: { fontSize: 13, fontWeight: '900', color: Colors.errorDark },
  statusText: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  confirmBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 6, marginTop: 6 },
  confirmBtnDisabled: { opacity: 0.6 },
  confirmBtnText: { color: Colors.white, fontSize: 11, fontWeight: '800' },
  reportedText: { fontSize: 11, fontWeight: '700', color: Colors.warningDark, marginTop: 4 },
  alertLine: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, padding: 12, gap: 8 },
  alertLabel: { flex: 1, fontSize: 12, fontWeight: '700', color: Colors.n700 },
  alertValue: { fontSize: 13, fontWeight: '900' },
  emptyCard: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.r12, borderWidth: 1, borderColor: Colors.n200, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Colors.n500 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: Colors.white, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, padding: Spacing.lg, gap: 8 },
  modalHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Colors.n300, alignSelf: 'center', marginBottom: 8 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: Colors.n900, marginBottom: 6 },
  inputLabel: { fontSize: 12, fontWeight: '800', color: Colors.n700 },
  input: { borderWidth: 1, borderColor: Colors.n200, backgroundColor: Colors.n50, borderRadius: Radius.r12, paddingHorizontal: 12, paddingVertical: 11, color: Colors.n900, fontWeight: '700' },
  textArea: { minHeight: 82, textAlignVertical: 'top' },
  saveBtn: { backgroundColor: Colors.primary, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center', marginTop: 6 },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: Colors.white, fontWeight: '900' },
  cancelBtn: { backgroundColor: Colors.n100, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center' },
  cancelBtnText: { color: Colors.n700, fontWeight: '800' },
});
