import { StyleSheet } from 'react-native';
import { Arena, Colors, Radius, Spacing } from '@ui/tokens/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Arena.bg },
  center: { justifyContent: 'center', alignItems: 'center', gap: 10, padding: 24 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: 'rgba(6, 16, 15, 0.96)',
    borderBottomWidth: 1,
    borderBottomColor: Arena.line,
    gap: 12,
  },
  headerBody: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: Arena.text },
  headerSub: { fontSize: 12, color: Arena.textMuted, marginTop: 1 },
  errorText: { fontSize: 14, color: Arena.textMuted },
  primaryBtn: { backgroundColor: Arena.neon, paddingHorizontal: 18, paddingVertical: 10, borderRadius: Radius.r8 },
  primaryBtnText: { color: Arena.bgDeep, fontWeight: '900' },
  scrollContent: { paddingBottom: 32 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: Spacing.lg },
  metricCard: { width: '48%', borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, backgroundColor: Arena.card, padding: 12 },
  metricLabel: { fontSize: 11, color: Arena.textSubtle, marginBottom: 6 },
  metricValue: { fontSize: 17, fontWeight: '900' },
  actions: { flexDirection: 'row', gap: 10, paddingHorizontal: Spacing.lg, paddingBottom: Spacing.md },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Arena.card,
    borderRadius: Radius.r12,
    borderWidth: 1,
    borderColor: Arena.line,
    paddingVertical: 12,
  },
  actionText: { fontSize: 12, fontWeight: '800', color: Arena.neon },
  actionPaid: { backgroundColor: 'rgba(34, 197, 94, 0.16)', borderColor: 'rgba(34, 197, 94, 0.24)' },
  actionPaidText: { fontSize: 12, fontWeight: '800', color: '#4ADE80' },
  filterBlock: { paddingHorizontal: Spacing.lg, gap: 8 },
  filterTitle: { fontSize: 12, fontWeight: '800', color: Arena.text },
  chips: { gap: 8, paddingRight: Spacing.lg },
  chip: { borderRadius: Radius.r999, borderWidth: 1, borderColor: Arena.line, backgroundColor: Arena.card, paddingHorizontal: 12, paddingVertical: 7 },
  chipActive: { backgroundColor: Arena.neon, borderColor: Arena.neon },
  chipText: { fontSize: 12, fontWeight: '700', color: Arena.textMuted },
  chipTextActive: { color: Arena.bgDeep },
  tabs: { flexDirection: 'row', margin: Spacing.lg, backgroundColor: Arena.cardSoft, borderRadius: Radius.r999, padding: 4, borderWidth: 1, borderColor: Arena.line },
  tabBtn: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: Radius.r999 },
  tabBtnActive: { backgroundColor: Arena.neon },
  tabText: { fontSize: 10, fontWeight: '700', color: Arena.textSubtle },
  tabTextActive: { color: Arena.bgDeep, fontWeight: '900' },
  section: { paddingHorizontal: Spacing.lg, gap: 8 },
  listSeparator: { height: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '900', color: Arena.text, marginBottom: 2 },
  sectionTitleSpaced: { marginTop: 18 },
  rowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: 12, gap: 10 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 13, fontWeight: '800', color: Arena.text },
  rowSub: { fontSize: 11, color: Arena.textMuted, marginTop: 3 },
  amounts: { alignItems: 'flex-end', maxWidth: 132 },
  paidText: { fontSize: 13, fontWeight: '900', color: '#4ADE80' },
  pendingText: { fontSize: 11, fontWeight: '700', color: '#FBBF24', marginTop: 2 },
  overdueText: { fontSize: 11, fontWeight: '700', color: '#F87171', marginTop: 2 },
  amountText: { fontSize: 13, fontWeight: '900', color: Arena.text },
  expenseText: { color: '#F87171' },
  expenseValue: { fontSize: 13, fontWeight: '900', color: '#F87171' },
  statusText: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  confirmBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r8, paddingHorizontal: 10, paddingVertical: 6, marginTop: 6 },
  confirmBtnDisabled: { opacity: 0.6 },
  confirmBtnText: { color: Arena.bgDeep, fontSize: 11, fontWeight: '900' },
  paidBadge: { backgroundColor: 'rgba(34, 197, 94, 0.16)', borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 5 },
  paidBadgeText: { color: '#4ADE80', fontSize: 11, fontWeight: '800' },
  reportedText: { fontSize: 11, fontWeight: '700', color: '#FBBF24', marginTop: 4 },
  alertLine: { flexDirection: 'row', alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, padding: 12, gap: 8 },
  alertLabel: { flex: 1, fontSize: 12, fontWeight: '700', color: Arena.textMuted },
  alertValue: { fontSize: 13, fontWeight: '900' },
  emptyCard: { alignItems: 'center', backgroundColor: Arena.card, borderRadius: Radius.r12, borderWidth: 1, borderColor: Arena.line, paddingVertical: 24, gap: 8 },
  emptyText: { fontSize: 13, color: Arena.textMuted },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: Arena.graphiteElevated, borderTopLeftRadius: Radius.r24, borderTopRightRadius: Radius.r24, padding: Spacing.lg, gap: 8 },
  modalHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: Arena.line, alignSelf: 'center', marginBottom: 8 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: Arena.text, marginBottom: 6 },
  inputLabel: { fontSize: 12, fontWeight: '800', color: Arena.textMuted },
  input: { borderWidth: 1, borderColor: Arena.neonBorder, backgroundColor: Arena.card, borderRadius: Radius.r12, paddingHorizontal: 12, paddingVertical: 11, color: Arena.text, fontWeight: '700' },
  textArea: { minHeight: 82, textAlignVertical: 'top' },
  saveBtn: { backgroundColor: Arena.neon, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center', marginTop: 6 },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: Arena.bgDeep, fontWeight: '900' },
  cancelBtn: { backgroundColor: Arena.cardSoft, borderWidth: 1, borderColor: Arena.line, borderRadius: Radius.r12, paddingVertical: 13, alignItems: 'center' },
  cancelBtnText: { color: Arena.text, fontWeight: '800' },
});
