import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../../../common/theme';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    borderRadius: Radius.r12,
    borderWidth: 0.5,
    borderColor: Colors.n200,
    marginBottom: Spacing.sm,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.n200,
  },
  dateText:  { fontSize: 12, fontWeight: '600', color: Colors.n700 },
  locText:   { fontSize: 11, color: Colors.n400, marginTop: 1 },
  body:      { padding: 12 },
  vsRow:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  teamBlock: { flex: 1, alignItems: 'center', gap: 4 },
  teamLogo:  { width: 40, height: 40, borderRadius: Radius.r8, backgroundColor: Colors.n100, alignItems: 'center', justifyContent: 'center' },
  teamName:  { fontSize: 11, fontWeight: '600', color: Colors.n700, textAlign: 'center' },
  vsBadge:   { fontSize: 13, fontWeight: '800', color: Colors.n400 },
  scoreBig:  { fontSize: 28, fontWeight: '800', color: Colors.n900, letterSpacing: 2 },
  tagsRow:   { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  tag:       { fontSize: 11, fontWeight: '500', paddingHorizontal: 10, paddingVertical: 3, borderRadius: Radius.r4 },
  tagCampo:   { backgroundColor: Colors.successLight, color: Colors.successDark },
  tagSociety: { backgroundColor: '#DBEAFE', color: '#1D4ED8' },
  tagFutsal:  { backgroundColor: '#F3E8FF', color: '#6B21A8' },
  progLabel: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  progLabelText: { fontSize: 11, color: Colors.n400 },
  progLabelVal:  { fontSize: 11, fontWeight: '600', color: Colors.primary },
  progBg:    { height: 6, backgroundColor: Colors.n200, borderRadius: Radius.r999, overflow: 'hidden' },
  progFill:  { height: 6, backgroundColor: Colors.primary, borderRadius: Radius.r999 },
  confPill:  { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.successLight, borderRadius: Radius.r999, paddingHorizontal: 10, paddingVertical: 3 },
  confText:  { fontSize: 11, fontWeight: '600', color: Colors.successDark },
});
